### ISSUE TITLE
Reivew cw/add-html2-reporter to make a SPA HL reporter

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall2#101]
https://github.com/inspec/inspec/tree/cw/add-html2-reporter

This was an idea that we already pushed to the inspec folks about updating the html reporter to just use a SPA version of HL - a bit modified - to save the results data into the Single page build of HL to make a much better version of the HTML reporter.

This is a good start but as you can see - it is not so pretty

@lukemalinowski did a lot of work with the Webpack build of HL so he may be a good resource

**Comment by Amndeep7** [comment]
Above link is broken, but I think this is the relevant pr: https://github.com/inspec/inspec/pull/5045

@aaronlippold due to them having merged the pr that I think is the one you're talking about, I'm closing this issue.  Re-open if there's something else that needs to be done.
