### ISSUE TITLE
Allow owners to change users group role

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#1027]
**Is your feature request related to a problem? Please describe.**
It currently isn't possible for an owner to edit a users role.

Once #1026 is resolved, the ability to click on that role should be added, and a dropdown should appear allowing the owner to change this setting.

**Comment by samuelsunvold** [comment]
8d125471f37768267eb8b1b1cfa4bb212f4d9663

**Comment by Amndeep7** [comment]
The associated PR needs to be reviewed and then merged
