### ISSUE TITLE
Support for custom base path in URL

### ISSUE THREAD

**Issue by virtualdom** [mitre/heimdall2#1069]
**Is your feature request related to a problem? Please describe.**
The hostname I am using to access Heimdall2 is shared amongst other services, but because Heimdall2 sets its base path as the root path `/`, it collides with the service that I already host at the root path.

**Describe the solution you'd like**
I would like for Heimdall2 to accept a custom, optional base path value. For example, if I provide a base path value of `/heimdall`, I would like all Heimdall2 endpoints to be nested under `/heimdall` (e.g. `/heimdall/users`, `/heimdall/server`, etc.).

**Describe alternatives you've considered**
Using a different subdomain is an option, but I do not have administrative access to our advanced DNS settings and cannot provision a subdomain myself easily.

**Desired Impact to Workflow**
N/A at the moment.

**Comment by camdenmoors** [comment]
Since this requires recompiling the frontend at build time which is not configurable we can't implement this feature. If this is still needed consider changing your Webpack configuration to support a different base URL.
