### ISSUE TITLE
CAAT doesn't distinguish multiple result sets

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#1107]
If more than one of the same type of result set are loaded for viewing (having common control ids), when exporting to CAAT only one set of information for each control id is listed, as opposed to each. This can be seen by loading the NGINX samples or red hat samples.

To distinguish each result set in the CAAT, it is safe to use the (as yet unused by us) 4th column "D": "Finding ID" to populate with the following information:

<filename> - Test <control_id>

e.g.,: my_rhel7_03012021.json - Test V-71999

**Comment by rbclark** [comment]
After discussion on this, I believe the best fix for this is to create a different worksheet for each file that is currently loaded.
