### ISSUE TITLE
Confusing error message on failed json import

### ISSUE THREAD

**Issue by Bialogs** [mitre/heimdall2#112]
Error message mentions inspecjs while link takes you to heimdall-lite and the error message is quite wordy because I believe its just whatever inspec-js outputs but we could probably think of something better to tell the end-users.

<img width="1446" alt="Screen Shot 2020-06-25 at 09 50 21" src="https://user-images.githubusercontent.com/3009651/85759807-3fa59580-b6df-11ea-9e3a-ac1b5b0d6afb.png">

**Comment by rbclark** [comment]
This seems to now be fixed in #1342
