### ISSUE TITLE
Sample selected bar in wrong position

### ISSUE THREAD

**Issue by Bialogs** [mitre/heimdall2#115]
When you click on Samples it shows the space above it as selected
<img width="151" alt="Screen Shot 2020-06-25 at 9 33 08 AM" src="https://user-images.githubusercontent.com/3009651/85757713-b477d000-b6dd-11ea-8edb-373cebf6ba7a.png">

**Comment by camdenmoors** [comment]
Closing as this is no occurs.

**Comment by rbclark** [comment]
This only happens on specific screen sizes, for example 1280x720

![specificscreensizes](https://user-images.githubusercontent.com/2308869/122121354-85c89d00-cdf9-11eb-83c7-751710ff4910.gif)
