### ISSUE TITLE
Switch to async pattern, add in process indicator for multiple file loading, with success and fail

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall2#117]

**Comment by rbclark** [comment]
@aaronlippold If this is only in reference to the loading of "Local Files" then it might be possible to consider this resolved. Heimdall currently shows a loading indicator which displays until the files are successfully uploaded.

![Screen Recording 2020-10-05 at 10 24 42 AM](https://user-images.githubusercontent.com/2308869/95205063-ddb2fc80-07b2-11eb-8312-8c62d56b5f92.gif)

**Comment by rbclark** [comment]
The only additional improvement on top of this would be adding some sort of loading notifier for Samples as well.
