### ISSUE TITLE
Create exportCAAT component with wizard for customizing output

### ISSUE THREAD

**Issue by lukemalinowski** [mitre/heimdall2#120]
Full Data: The current function of the CAAT component.

Condensed/Interactive:
Use Case:
A user wants to fold each NIST Sub-Family into single row rather than multiple rows for every result. If they select the condensed mode - we will have a 'wizard model' come out and ask what 'standard text' we want for each column for that Sub-Family Finding - walking them across the spreadsheet.

As the user is walking though each sub-family step - It would be good if we can have another model that has a datatable of the 'detailed results' of those findings for the sub-family that they could open and close for review if needed.

UX consideration: we can we can suggest a 'default' answer -
a) like Severity ( if 8 / 10 are high or they are all the same) or
b) if they have already provided an answer - such as 'System Name' - that is unlikely to change. ( perhaps the last answer is good enough for most cases ).
c) *Could use vuetify modal*

Once they walk through, they can save it as a csv/xlsx.

Derived from https://github.com/mitre/heimdall-vue/issues/14

**Comment by Amndeep7** [comment]
It seems like we have a CAAT export so I'm gonna close this issue unless there's something missing from the functionality that currently exists.
