### ISSUE TITLE
[BUG] Issue running Heimdall Server

### ISSUE THREAD

**Issue by supersoaker9928** [mitre/heimdall2#1267]
**Describe the bug**
Cannot run Heimdall Server

**To Reproduce**
Follow the steps in README.md and get an error

**Expected behavior**
Should run it properly

**Screenshots**
https://gyazo.com/b41e9680e74d3436736ad58b1c3af15b
https://gyazo.com/e9aef46cbd328b5ff58602fa3bc01f7a

**Desktop (please complete the following information):**
Centos 7

**Additional context**
I am followed every step, yarn frontend start:dev is working properly however, yarn backend start:debug gives the weird error when I go to the page.

**Comment by rbclark** [comment]
Are you attempting to run a production build of Heimdall or a development build? It sounds like you are trying to start it in development mode, which brings up 2 ports, 1 for the frontend and 1 for the backend. You are then navigating to the backend port not the frontend port which causes the error you described.

Please either use a production build where everything runs from 1 server, which you can do by running:

```
yarn build
yarn start
```

or you can start in development mode by running:

```
yarn start:dev
```

and then navigating to http://localhost:8080

**Comment by rbclark** [comment]
@supersoaker9928 Did this get you past your issue?

**Comment by georgedias** [comment]
Robert,

Nope, still working on it now, searching on some of the error messages

From: Robert Clark ***@***.***>
Sent: Wednesday, April 28, 2021 2:44 PM
To: mitre/heimdall2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] Re: [mitre/heimdall2] [BUG] Issue running Heimdall Server (#1267)


@supersoaker9928<https://github.com/supersoaker9928> Did this get you past your issue?

**Comment by supersoaker9928** [comment]
First of all, sorry for the late rply @rbclark, second with yarn start:dev the localhost:8080 doesnt work

**Comment by rbclark** [comment]
Are you receiving any specific error when attempting to start the server?

**Comment by supersoaker9928** [comment]
Got it working I had to do the yarn build part so thanks for that! however, I am in a constant loop now - logging in and getting returned back to the home page to login again, any idea? No error is popping up and it is showing successfully logged in https://gyazo.com/01277355212a6848df4f43857b01fc83

**Comment by rbclark** [comment]
Could you right click and open the developer console to see if you are getting any errors there?

**Comment by rbclark** [comment]
Also can you tell me the full set of commands you are running and what values you have in your .env file? (minus the secret ones)

**Comment by supersoaker9928** [comment]
Console error: https://gyazo.com/68f5a78a9b2bff4f70e34642b9cb0a3a
.enf file: https://gyazo.com/b3ebe420f3f338b45a2a0e88bb8541af

Commands used: yarn start and then going localhost:3000

**Comment by supersoaker9928** [comment]
Fixed it, I changed the JWT_EXPIRE_TIME to 1h and now everything is working properly. Thank you for the assistance!
