### ISSUE TITLE
Move Tools sidebar options to Export button

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#133]
Instead of having the 3 export tools options on the sidebar, as pictured

<img width="371" alt="Screen Shot 2020-09-03 at 3 04 56 PM" src="https://user-images.githubusercontent.com/2308869/92156415-ef416700-edf6-11ea-9c76-cd058d79809e.png">

the app should have a dropdown with these 3 export options on it

<img width="713" alt="Screen Shot 2020-09-03 at 3 04 29 PM" src="https://user-images.githubusercontent.com/2308869/92156295-c5884000-edf6-11ea-9701-5f0645956e04.png">

**Comment by aaronlippold** [comment]
Seems like a good idea to me
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
