### ISSUE TITLE
Move "Help" and "About" text to the Heimdall Logo

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#134]
Clicking on the Heimdall Logo in the top right of the app currently does nothing.

<img width="342" alt="Screen Shot 2020-09-03 at 3 08 06 PM" src="https://user-images.githubusercontent.com/2308869/92156629-47786900-edf7-11ea-9c23-813dba447d68.png">

It should instead bring up a dropdown providing the user with a Help and About button. Once that is moved the "Help" and "About" buttons should be removed from the sidebar.

**Comment by aaronlippold** [comment]
Agreed and we should add the version and release info there as well.
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by camdenmoors** [comment]
I am unable to assign myself this, but I am going to be working on it if someone wants to assign me.
