### ISSUE TITLE
[BUG]The About information is outdated

### ISSUE THREAD

**Issue by dmokllm** [mitre/heimdall2#136]
**Describe the bug**
The Changelog and Github information on the About modal is outdated.

**To Reproduce**
1. Go to view uploaded files.
2. Click on the hamburger menu at the top to open the sidebar.
3. Towards the bottom of the sidebar, click the 'About' link.
4. Note the URLs.

**Expected behavior**
The URLs should point to the new Github repo for Heimdall 2.

**Screenshots**
![about](https://user-images.githubusercontent.com/68665347/92164193-f1112780-ee02-11ea-8f7b-7d84e51b22e8.PNG)

**Comment by rbclark** [comment]
Can you verify your branch is up-to-date? https://heimdall-lite.mitre.org/ shows the correct information and is built off the latest release of master (which was this morning).
