### ISSUE TITLE
[BUG] ApexCharts fail to clear center text when filters are cleared

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#140]
**Describe the bug**
![Screen Recording 2020-09-09 at 1 12 00 PM](https://user-images.githubusercontent.com/2308869/92630861-7894e580-f29e-11ea-8389-3c1923e5a990.gif)

**To Reproduce**
1. Load any file (or sample)
2. Click on Severity Counts or Status Counts donuts.
3. Click again to clear the filter
4. See the "Low", "Medium", "High", "Pass", or "Failed" filter is still present even after the filter is cleared

**Expected behavior**
The filter should not be visible if the filter is not active.

**Screenshots**

**Comment by rbclark** [comment]
This bug has turned out to be related to multiple issues with apex charts itself, one of which is https://github.com/apexcharts/vue-apexcharts/issues/285

**Comment by Bialogs** [comment]
Closed by 8e07e0b272124d8be71f3ac8ba9f14a94af66f82
