### ISSUE TITLE
Solve Issues found by LGTM scan

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#149]
LGTM is setup to scan every PR for code issues. This prevents new issues from being introduced into the codebase, however we still need to solve the existing issues.

Issues can be found at: https://lgtm.com/projects/g/mitre/heimdall2/?mode=list

- [x] Frontend

- [x] backend

**Comment by Amndeep7** [comment]
All issues are resolved besides the storage one which will require significant refactoring.
