### ISSUE TITLE
Implement Clustering on Backend

### ISSUE THREAD

**Issue by camdenmoors** [mitre/heimdall2#1549]
**Is your feature request related to a problem? Please describe.**
As it stands the Heimdall backend is tied to a single thread. Implementing clustering on deployments that have multiple cores could see a performance boost on backend performance.

**Describe the solution you'd like**
Using an [app cluster](https://dev.to/danudenny/clustering-nest-js-2mj7).

**Describe alternatives you've considered**
[PM2 Clustering](https://pm2.keymetrics.io/docs/usage/cluster-mode/#cluster-mode)

**Comment by rbclark** [comment]
I'm not sure the application is at the point where it needs this yet, also it is already possible to scale this up just using multiple Docker containers with nginx in front of it without any code modifications.

https://github.com/nestjs/docs.nestjs.com/issues/1067#issuecomment-597070876

**Comment by rbclark** [comment]
Additional information can be found here: https://stackoverflow.com/questions/50203408/docker-compose-scale-x-nginx-conf-configuration
