### ISSUE TITLE
Is there a docker image?

### ISSUE THREAD

**Issue by KyyB** [mitre/heimdall2#156]
Previously, there was but whenever I run, it said couldn't find the docket image locally

**Comment by Bialogs** [comment]
There was never a Docker image in this repository. 

Please track https://github.com/mitre/heimdall2/pull/127 for the status of a docker image that incorporates Heimdall Enterprise Server 2.0 and Heimdall Lite 2.0 together.

For the old Heimdall Server version 1.0 please see https://github.com/mitre/heimdall

For an older version of Heimdall Lite you can pull with `docker pull mitre/heimdall-lite:latest`

**Comment by KyyB** [comment]
After running that Docker command for pulling image. When I run it, it says "unable to find image locally" which is weird
