### ISSUE TITLE
Allow role changes for identity provider login created users.

### ISSUE THREAD

**Issue by rlakey** [mitre/heimdall2#1640]
**Is your feature request related to a problem? Please describe.**
An LDAP user logs in without a previously created local account with the same email address and we are unable to edit the users role because it states some settings are managed by your identity provider and the save button is greyed out even though I can select the admin or user role.

**Describe the solution you'd like**
Allow role changes for locally created users.

**Describe alternatives you've considered**
None

**Desired Impact to Workflow**
None

**Comment by rbclark** [comment]
@rlakey this is now fixed and will be available in the next release of heimdall server.
