### ISSUE TITLE
[BUG] Angle brackets and text within them are removed when shown in Heimdall

### ISSUE THREAD

**Issue by Amndeep7** [mitre/heimdall2#1702]
**Describe the bug**
Angle brackets and text within them are removed when shown in Heimdall.

**To Reproduce**
1. Generate an HDF file that has text inside of angle brackets (ex. "code_desc": "<root_account>")
2. Open that HDF file up in Heimdall.

**Expected behavior**
Text to be shown exactly as written in the HDF file.

**Screenshots**
<img width="908" alt="image" src="https://user-images.githubusercontent.com/2015821/127014424-40bf6377-6550-4252-b87b-271323597de1.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.4
 - Browser: Firefox
 - Version: 90.0.1

**Additional context**
[prowler_example-hdf.json.txt](https://github.com/mitre/heimdall2/files/6879351/prowler_example-hdf.json.txt)
Github only allows uploading certain filetypes so just convert it back into .json.

**Comment by sesheikholeslam** [comment]
The reason the angle brackets are not displaying in the results view is because symbols such as the angle brackets and ampersands '&' are html reserved symbols. So in order to have them display we need to encode the substrings before hand.
