### ISSUE TITLE
Docker image for Heimdall

### ISSUE THREAD

**Issue by kclinden** [mitre/heimdall2#173]
**Is your feature request related to a problem? Please describe.**
It would be awesome if there was a docker image provided for running heimdall. 

**Describe the solution you'd like**
Using DockerHub or GitHub's Container Registry, provide a prebuild docker image.

**Comment by aaronlippold** [comment]
There is a container

**Comment by Amndeep7** [comment]
In particular, please look here: https://hub.docker.com/r/mitre/heimdall2

**Comment by rbclark** [comment]
Are you looking to run Heimdall lite or heimdall server? We recently updated our README to include instructions on how to run either version, https://github.com/mitre/heimdall2#general-deployment

**Comment by kclinden** [comment]
Yep this can be closed now. Should have spent more time searching. 😨
