### ISSUE TITLE
Ensure Dockerfiles for both frontend and Backend are updated with new install system

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall2#187]
The Frontend and Backend Dockerfile need a bit of love given our switch to yarn. We need to update it so we can build and publish in the right namespace 'aka MITRE' the lite and server version.

The GCP folks have asked us to submit PRs for their profiles highlight using the docker container of light in the profiles.

We also need to break out the README a bit so there is a development workflow for both server and lite and a run the app as server and lite from the published sources - aka npx and docker. (Solved in https://github.com/mitre/heimdall2/pull/233)

**Comment by rbclark** [comment]
This is a continuation of the work @rx294 has been doing as part of https://github.com/mitre/heimdall2/pull/127

**Comment by rx294** [comment]
Noting that the monorepo deployment docker image is already using yarn https://github.com/mitre/heimdall2/blob/master/Dockerfile

**Comment by rbclark** [comment]
Additionally, I believe the frontend standalone dockerfile will need to be moved to the root of the repository and renamed to something like `Dockerfile.lite` in order to allow it to have access to the `yarn.lock` file.
