### ISSUE TITLE
[Database Results] Prevent uploading the same result.

### ISSUE THREAD

**Issue by Bialogs** [mitre/heimdall2#201]
The same result can be saved multiple times and a new record will be created in the database for each save by just clicking the Save button in the UI over and over. The application should disable the save button, show some descriptive mouseover text saying "Saved to database" and maybe even show a Save button with a small checkbox on it making it abundantly clear to the user that they cannot save the result again. It should be possible to keep track of this by checking whether or not the Result or Profile has a database_id.

Depends #181.

**Comment by ejaronne** [comment]
I'm not seeing the difference between current release and staging of this. Maybe I'm not understanding the bug.

**Comment by rbclark** [comment]
This may have gotten fixed a release earlier than we originally planned. If the save button is greyed out after clicking save on a result then this is fixed.
