### ISSUE TITLE
Add the Ability to Convert All Sites with ZapMapper

### ISSUE THREAD

**Issue by camdenmoors** [mitre/heimdall2#2016]
Currently the `ZapMapper` mapper uses a filter function to grab a specific site as passed, however, it would be nice to associate each site with an individual profile inside the HDF (or return multiple ExecJSONs like the Nessus/Snyk mapper).

**Comment by Amndeep7** [comment]
duplicate: https://github.com/mitre/heimdall2/issues/2412
