### ISSUE TITLE
Evaluations Controller

### ISSUE THREAD

**Issue by Bialogs** [mitre/heimdall2#21]
- [x] Evaluation DTO

- [x] Create Method

- [x] Read Methods (Index and by id)

- [x] Update Methods

- [x] Destroy Methods

- [x] New policy database seed files to allow users to perform actions on evaluations

- [x] Evaluation routes are behind authentication guards

- [x] Evaluation routes are behind authorization guards

- [x] Evaluation Module imported into Application module

**Comment by rbclark** [comment]
Closed by #794
