### ISSUE TITLE
[BUG] Creating Evaluation Tags Gets Blocked by Popup

### ISSUE THREAD

**Issue by camdenmoors** [mitre/heimdall2#2197]
Somehow an update has caused the "Create New Tag"  message to overlap the textbox box for inputting the evaluation tag name. Typing does not allow inputting into the box.

![image](https://user-images.githubusercontent.com/66680985/142039068-8d040752-a0e0-4f0f-85f7-bc35866f0537.png)

**Comment by rlakey** [comment]
I was just about to open an issue for this exact issue but looks like you have it covered!
