### ISSUE TITLE
Load persistence in server mode?

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#223]
When in server mode, shouldn't results loaded from the database persist until logout? Currently hitting F5 clears all loads.

Database connections persist as part of the server build process. In the future, will admins be able to "point to" different databases as easily as the forms used to point to Splunk and S3.

A step further: will users  be able to save Splunk and S3 connection setting in the server so they are available (at least for that user). 

Bringing it all together: server mode with a database, Splunk source and S3 source saved and configured, and results loaded from all 3 sources. Hit F5, and those loaded results stay loaded...

**Comment by rbclark** [comment]
The results are not loaded into the database until the user actually clicks the save button on the Sidebar. Is the request here to make the Local Upload automatically save into the database when in server mode or would you like results to be saved into local storage in both server and lite mode so that reloads persist results?

**Comment by ejaronne** [comment]
None of the above. 
Let's say I've saved things into the database previously. I log in and load some of them to view. I hit F5. Right now everything I loaded unloads. Why not keep them there until I actually log out? Heimdall Server 1.0 doesn't clear the loaded result when I hit F5.

**Comment by ejaronne** [comment]
In other words, in server mode, I don't have to do *everything* in memory of the browser. I can begin to maintain more and more state in the server to make the user experience less ephemeral, right?

**Comment by rbclark** [comment]
Depends on #231.
