### ISSUE TITLE
Only allow users to "Peek Password" on the Signup page

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#225]
If possible, don't provide the ability to see the entered password if auto-filled by browser. While I had my browser cache my password, I didn't need to be able to see if what was populated was indeed the correct password. And neither should anyone else! 

This was further exacerbated because my browser kept offering the same login credentials to the Splunk and S3 settings areas, all with ability to view the password again. A little too helpful.

For signing up, sure it is very helpful. But not much after that. If you can distinguish between hand-typed (allow display) vs auto-filled (don't allow display), that would be a fair compromise for now.

**Comment by rbclark** [comment]
I am fine with removing the "Show Password" feature completely, however trying to detect whether or not it is enabled seems a little fragile. It is very possible to just display the password using inspector tools normally meaning there isn't much of a security benefit to removing the "Show Password" feature, unless there is another reason you want it removed.

**Comment by ejaronne** [comment]
I didn't say remove it completely. On the other hand, my overzealous browser cache placed it:
![image](https://user-images.githubusercontent.com/34140975/94091548-82fac780-fde6-11ea-9318-215618d643f9.png)
and here:
![image](https://user-images.githubusercontent.com/34140975/94091590-9efe6900-fde6-11ea-9a79-59d0207d763a.png)
and here:
![image](https://user-images.githubusercontent.com/34140975/94091616-ae7db200-fde6-11ea-9a9c-191374bca3be.png)

So if I don't lock my screen when stepping away and someone strolls by, there's just too much opportunity.

I don't see real apps offer this much help everywhere. Only for sign-up and typed in passwords.

**Comment by aaronlippold** [comment]
If I am creating a new password - being able to see it while I am doing it on both sides is useful

**Comment by rbclark** [comment]
My concern on this one is there is no straightforward way to detect if autofill was used for all browsers, so trying to implement the logic to hide the password show button has the potential to be extremely fragile: https://stackoverflow.com/questions/11708092/detecting-browser-autofill

It is somewhat straightforward to detect in chrome but not in FF or IE.

**Comment by ejaronne** [comment]
So just restrict it to sign up for now.
