### ISSUE TITLE
csv exporter doesn't work with overlay result sets

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#2258]
Can be reproduced using Triple Overlay Example in Heimdall.

The csv produces profile errors for anything that isn't Not Applicable.

**Comment by aaronlippold** [comment]
Given that all of our exporters should be using inspec JS on the back end I didn't think this kind of error was possible. Is there anyway we can make sure that our library abstracts away this mistake and makes it almost impossible to occur.

**Comment by ejaronne** [comment]
But first, please let's fix this the old fashioned way to expedite a fix. Folks in the field using overlays are noticing. Should we open a separate issue for improving our library?
