### ISSUE TITLE
Description fields and subfields don't render on the details sub-tab correctly.

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#2283]
Reproduce using the red hat 7 sample in heimdall:
Under the code sub-tab, for example the check text is easy to read, mainly due to CR/LF working:
![image](https://user-images.githubusercontent.com/34140975/145311472-5118c63d-6ed4-4689-aded-e209e18ca0d0.png)

But under the Details sub-tab, these same fields are run-on:
![image](https://user-images.githubusercontent.com/34140975/145311542-d651ca5e-aa39-4544-af6f-d41c76d93f08.png)

**Comment by camdenmoors** [comment]
Closed in https://github.com/mitre/heimdall2/pull/2287
