### ISSUE TITLE
[BUG]AD Authentication not working

### ISSUE THREAD

**Issue by KodySalak** [mitre/heimdall2#2302]
**Describe the bug**
When I try to log in with LDAP, I get an "unauthorized" no matter what the settings are for the LDAP variables in the .env_prod/.env file.

**To Reproduce**
1. set LDAP settings as follows
2. LDAP_ENABLED=true
LDAP_HOST=ADServer.domain.local
LDAP_BINDDN="CN=Heimdall SA,CN=Users,DC=domain,DC=local"
LDAP_PASSWORD="RedactedPassword"
LDAP_SEARCHBASE="DC=domain, DC=LOCAL"
3. Start Heimdall
4. Attempt a login and see "Unauthorized" error

**Expected behavior**
Login from AD using the binding credentials provided.

**Screenshots**
[Screenshot](https://prnt.sc/22vczeh)

**Desktop (please complete the following information):**
 - OS: Windows 11, 10
 - Browser Chrome
 - Version 96.0.4664.110

**Additional context**
Per my screenshot, it looks like there is a chrome error about a request being inline. I am not sure if this is what is causing it to not work, but I deployed the Heimdall instance at work and at home again last night, and both are acting exactly the same with chrome up to date. I'm at a loss of what to do, and I'm thinking chrome is blocking something at the moment.

**Comment by camdenmoors** [comment]
Hi Kody,

This appears to be an issue with your backend not finding the user and not the frontend. For your LDAP searchbase, can you try using `"OU=Users, DC=<yourdomain>, DC=local"`, assuming standard AD configuration, users are stored in the Users OU.

If this helps: https://github.com/mitre/heimdall2/wiki/Environment-Variables-Configuration#ldap

**Comment by KodySalak** [comment]
No dice with that either... the users of this tool are in a different OU than the default Users, so I pointed it to the correct OU for that. 

I can get to my DC with telnet from the server that's running heimdall 

I was getting all of my config settings from that wiki page... I am confused on what needs to be in quotes are not since there aren't examples on some of them. does that all look correct from my initial post? 

Are there any logs or anything else I could look at to narrow it down? Is there any docker-specific settings I need to change? 

(I am relatively new to docker so I am trying my best!! :P)

**Comment by camdenmoors** [comment]
> I am confused on what needs to be in quotes 
The quotes just ensure the string is recognized correctly

Can you try copying the distinguishedName for each object in the .env file? For Windows Server:

 - Open AD Users and Computers
 - View
 - Enable Advanced Features
 - Right-click the Object you want to copy the path for
 - Properties
 - Attribute Editor
 - Select distinguishedName
 - Edit
 - Copy

Apologies for the slow response, last week was a busy one. If you have time this week or next week I can schedule a teams call if these steps don't help.

**Comment by KodySalak** [comment]
Service Account for the BindDN: CN=Heimdall SA,CN=Users,DC=domain,DC=local
Searchbase for Users: OU=IT,OU=Win10,DC=domain,DC=local

**Comment by KodySalak** [comment]
Apologies for the ghosting! Been a wild month and a half. 

I just noticed that when I run `sudo docker ps` on the container VM that's running Heimdall, I don't see 389 being forwarded... Could this be the cause? 

Output currently:
```
sudo docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED      STATUS      PORTS                                                                      NAMES
d1d2470bf620   nginx:alpine                     "/docker-entrypoint.…"   8 days ago   Up 8 days   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   heimdall_nginx_1
9eddfb70c3dc   mitre/heimdall2:release-latest   "docker-entrypoint.s…"   8 days ago   Up 8 days   0.0.0.0:49153->3000/tcp, :::49153->3000/tcp                                heimdall_server_1
a0db2adaf7a7   postgres:13                      "docker-entrypoint.s…"   8 days ago   Up 8 days   5432/tcp                                                                   heimdall_database_1
```

**Comment by KodySalak** [comment]
Disregard my previous comment - I was thinking backwards! 

I checked with my network engineer and I am not seeing any traffic being sent to the Domain Controller... I am still unsure why this isn't working as intended.

**Comment by KodySalak** [comment]
Okay, looks like I had the .env-prod file in the wrong place - causing the configuration to not take effect(??). 

I copied the .env-prod file to /apps/backend and then I was finally able to see my Heimdall Service Account (HeimdallSA) hit my domain controller with a logon/logoff, but I am still getting Unauthorized.

I have tried many searchbases, including "DC=domainName,DC=local" and "OU=IT,OU=AnotherOU,DC=domainName,DC=Local". 

I have also tried the following searchfilters under both the above searchbases with no luck at getting in:
```
- nothing at all
- (memberOf:1.2.840.113556.1.4.1941:=CN=ENT.Heimdall.Users,CN=Users,DC=domainName,DC=local)
- (&(objectclass=user)(memberOf=cn=ENT.Heimdall.Users,cn=Users,dc=domainName,dc=local))
- (&(objectclass=inetOrgUser)(memberOf=cn=ENT.Heimdall.Users,cn=Users,dc=domainName,dc=local))
```

**Comment by KodySalak** [comment]
Got it working finally!

I needed to change the password I was using. Because I was using `!!` in the beginning of the password, it wasn't working. Once I changed the password, all was well. Please be sure to document this. 

Also, as mentioned before, the location of the .env-prod file is still questionable. I had in `/apps/backend/`, as well as `.` and it was working just fine in the `.` after I got the AD Authentication working again. Which one is it? lol. 

Thanks.
