### ISSUE TITLE
Automatically publish Heimdall lite to npx on Release

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#232]
Whenever we release a version of heimdall-lite, it should use GH Actions to automatically create a new version on NPM and Github Packages.

We already have an equivalent workflow implemented for Ruby packages, may be able to borrow some from it: https://github.com/mitre/inspec_tools/blob/master/.github/workflows/release.yml

@aaronlippold are we intending to push to both https://www.npmjs.com/package/@mitre/heimdall-lite and https://www.npmjs.com/package/heimdall-lite?

**Comment by aaronlippold** [comment]
I would rather have a single location - under the right organational scoping as you all would expect from a developer perspective. Aka - if you would expect all MITRE npm packages to be under the @mitre org then I am happy to do that. @Amndeep7 may have thoughts as well. Secondly, we are also looking at publishing under the GitHub Packages world as well, and I had thought our general rule was going to be first souce is the GitHub package repo, and our second source is npm.org and dockerhub etc. Do I have it right in my head?

**Comment by Amndeep7** [comment]
IMO org/name is better esp with iirc some policy changes that came out this past year where MITRE wants to get more recognition for its work.  Furthermore, we have other products/libraries that are often used together so having an umbrella org that one can easily click makes it easy for someone to explore our offerings.

I'll leave the second part of your comment to @rbclark.

**Comment by rbclark** [comment]
My attack plan going forward was to just push to both NPM and Github packages and let users choose which they pull from. I believe NPM is still going to be the preferred choice of users. It is a little strange to me that Github even offers packages since npm is now owned by Github.

As for the namespace part of things, in that case we should go ahead and somehow deprecate the `heimdall-lite` npm package and just point users to `@mitre/heimdall-lite` instead, if such a thing is possible.

**Comment by aaronlippold** [comment]
```
Configuring the Plugin
The html2 reporter requires no configuration to function. However, two options--alternate_css_file and alternate_js_file--are available for customization. The options are set in the JSON-formatted configuration file that Chef InSpec consumes. For details, see our configuration file documentation.

For example:

{
  "version": "1.2",
  "plugins": {
    "inspec-reporter-html2": {
      "alternate_js_file":"/var/www/js/my-javascript.js",
      "alternate_css_file":"/var/www/css/my-style.css"
    }
  }
}
alternate_css_file
Specifies the full path to the location of a CSS file that will be read and inlined into the HTML report. The default CSS will not be included.

alternate_js_file
Specifies the full path to the location of a JavaScript file that will be read and inlined into the HTML report. The default JavaScript will not be included. The JavaScript file should implement at least a pageLoaded() function, which will be called by the onload event of the HTML body element.
```
Does this mean we could just overlay our layout and static js and css that webpacker creates to just 'override' the hml2 reporter?

**Comment by rbclark** [comment]
Fixes https://github.com/mitre/heimdall2/issues/48 https://github.com/mitre/heimdall2/issues/71 https://github.com/mitre/heimdall2/issues/103 https://github.com/mitre/heimdall2/issues/49
