### ISSUE TITLE
asff_mapper not parsing ASFF json

### ISSUE THREAD

**Issue by jtconnor** [mitre/heimdall2#2402]
Hi, I'm trying to use the asff_mapper.  The documention includes the asff_mapper, but this mapper seems to be missing from the current release version of heimdall_tools:

```
▶ heimdall_tools --version
1.3.48
▶ heimdall_tools asff_mapper
Could not find command "asff_mapper".
Did you mean?  "sarif_mapper"
```

How should I use the asff_mapper?  Do I need to build and run from repo source?

**Comment by camdenmoors** [comment]
This issue is now considered stale, please let us know if you have any issues or have further questions.
