### ISSUE TITLE
[BUG] Copying the API key is not working

### ISSUE THREAD

**Issue by stdevel** [mitre/heimdall2#2435]
**Describe the bug**
When creating an API key for a particular user, the key can't be copied to clipboard. It can also not be copied from the website's source code as it is truncated.

**To Reproduce**
1. Go to 'User Info'
2. Click on 'Show API keys'
3. Scroll down and click to 'Add API key'
4. Enter the current user password and click 'OK'
5. Once created, click 'Copy this API key'
6. Press CTRL+V on any application, e.g. text editor
7. The key is not copied

**Expected behavior**
The API key is copied to the clipboard. It would also be helpful to see the full API key in the webpage source code.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.04 (Ubuntu 20.04 LTS)
 - Browser: Mozilla Firefox and Google Chromium 
 - Versions: 95.0.1 and 83.0

**Comment by camdenmoors** [comment]
This seems to be an issue with access to the clipboard from how the browser is running (are you using snaps by chance?) 

I'll make a PR that shows the entire key on generation, but in the meantime you should be able to see the generated key in the network tab of dev tools.
