### ISSUE TITLE
Test asff2hdf against SecurityHub data from hdf2asff

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#2508]
asff content in AWS SecurityHub generated by saf convert:asff2hdf may need extra "pre-mappings" in order to completely reproduce the  original hdf.

**Comment by Amndeep7** [comment]
Copying @ejaronne's text from the other issue:

To assist asff2hdf in reconstituting the original hdf from asff content created using hdf2asff, add the following core control Types to hdf2asff's output:

    controls.id
    controls.title
    controls.impact

**Comment by Amndeep7** [comment]
@ejaronne @camdenmoors could be missing it, but don't see where yall are moving over the platform information.

**Comment by Amndeep7** [comment]
@ejaronne @camdenmoors how do yall wanna handle the top level profile information (name, version, title, all the way through attributes, depends, etc.)?  the findings that we get can be an amalgamation of findings from not just previously hdf ones but also anything else that was uploaded into sechub and wasn't previously filtered out.  consequently, we can't assume that the top level profile information from the first finding in the list applies to them all.  currently, my plan is to surface that information under a tag for a given control, but this is the first example where i think we're not gonna be able to maintain any parity with the original file

**Comment by Amndeep7** [comment]
Copying @ejaronne's text from the other issue:

> To simplify asff2hdf, when using hdf2asff add these Types:
> ASFF/Converter/mitre-saf-hdf2asff
> ASFF/Converter_version/1.0.5 linux-x64 node-v12.16.2 <- if possible

Currently I have it set to add something similar to "MITRE/SAF/2.6.9-hdf2asff".

**Comment by Amndeep7** [comment]
@camdenmoors would appreciate it if we could leverage https://github.com/mitre/heimdall2/pull/2606 to hold all the changes to the reverse mapper.  Currently it is just the saf version commit, but I will shortly be adding another commit to make 'Tags/whatever/array, values' look like 'Tags/whatever/[array, values]'
