### ISSUE TITLE
Correct release link in about statement

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#2519]
![image](https://user-images.githubusercontent.com/34140975/152373684-aa7bc898-f950-4715-ae47-b6c5358cef75.png)

should be https://github.com/mitre/heimdall2/releases ?

**Comment by camdenmoors** [comment]
Closed in https://github.com/mitre/heimdall2/commit/50b03fff501bb0dcc4eed770cb53c97acf4d2d11
