### ISSUE TITLE
Create a Static Output of Heimdall-lite with pre-populated results

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#253]
It would be beneficial to create an inspec plugin from this once it exists.

**Is your feature request related to a problem? Please describe.**
I would like to leverage heimdall-lite to create simple HTML results as an artifact of my CI runs.

**Describe the solution you'd like**
Automatically generating a heimdall-lite static page which contains pre-populated results after every run would make it very easy to view results in heimdall-lite as part of a CI pipeline (similar to how simplecov has a HTML reporter). 

**Desired Impact to Workflow**
This would remove the step of downloading the `result.json` and standing up heimdall-lite just to view an HTML result.

**Comment by aaronlippold** [comment]
This would be a great use case to use an inspec reporter plugin

**Comment by aaronlippold** [comment]
Review the html2 reporter as an example

**Comment by aaronlippold** [comment]
https://github.com/inspec/inspec/tree/master/lib/plugins/inspec-reporter-html2

**Comment by aaronlippold** [comment]
We may be able to actually borrow from this as well

**Comment by aaronlippold** [comment]
so what I would see in the end would be `inspec-reporter-heimdall-lite` or something

**Comment by aaronlippold** [comment]
and if we got that down `inspec-reporter-disa-checklist` would be another

**Comment by aaronlippold** [comment]
Configuring the Plugin
The html2 reporter requires no configuration to function. However, two options--alternate_css_file and alternate_js_file--are available for customization. The options are set in the JSON-formatted configuration file that Chef InSpec consumes. For details, see our configuration file documentation.

For example:

{
  "version": "1.2",
  "plugins": {
    "inspec-reporter-html2": {
      "alternate_js_file":"/var/www/js/my-javascript.js",
      "alternate_css_file":"/var/www/css/my-style.css"
    }
  }
}
alternate_css_file
Specifies the full path to the location of a CSS file that will be read and inlined into the HTML report. The default CSS will not be included.

alternate_js_file
Specifies the full path to the location of a JavaScript file that will be read and inlined into the HTML report. The default JavaScript will not be included. The JavaScript file should implement at least a pageLoaded() function, which will be called by the onload event of the HTML body element.
Does this mean we could just overlay our layout and static js and css that webpacker creates to just 'override' the hml2 reporter?

**Comment by rbclark** [comment]
Superseeded by https://github.com/mitre/heimdall2/issues/1242
