### ISSUE TITLE
hdf2asff - add Type: "ASFF/Converter/mitre-saf-hdf2asff" and version if possible

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#2605]
To simplify asff2hdf, when using hdf2asff add these Types:
ASFF/Converter/mitre-saf-hdf2asff
ASFF/Converter_version/1.0.5 linux-x64 node-v12.16.2  <- if possible

**Comment by Amndeep7** [comment]
Duplicate: https://github.com/mitre/heimdall2/issues/2508
