### ISSUE TITLE
`hdf2asff`: replace slashes in `profile.name` when creating the profile info finding

### ISSUE THREAD

**Issue by ben-harvey** [mitre/heimdall2#2633]
As noted in the comments for this constant, the AWS API will fail an import if the `Types` field of ASFF contains more than 2 forward slashes:
https://github.com/mitre/heimdall2/blob/5800edfd37f1903dd4501191731a3f22be989bed/libs/hdf-converters/src/converters-from-hdf/asff/reverse-asff-mapper.ts#L29

In `createProfileInfoFindingFields`, the `profile.name` can contain forward slashes (e.g. for JSON generated by the Snyk CLI, the value is `Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities`, and these should be replaced in the same manner as elsewhere.
https://github.com/mitre/heimdall2/blob/5800edfd37f1903dd4501191731a3f22be989bed/libs/hdf-converters/src/converters-from-hdf/asff/transformers.ts#L391

**Comment by aaronlippold** [comment]
Thanks @ben-harvey I will have the guys look into the best way to handle this
