### ISSUE TITLE
[BUG] Export to HTML test results are empty

### ISSUE THREAD

**Issue by rlakey** [mitre/heimdall2#2926]
**Describe the bug**
Exporting a result to an HTML report does not display the test results for a control

**To Reproduce**
1. Load a result
2. Export to HTML and choose manager or administrator report
3. View report
4. Test results are empty

**Expected behavior**
Able to determine test results for each control in the result

**Screenshots**

![image](https://user-images.githubusercontent.com/14838339/163848728-b5ba41d1-575e-4f19-9229-2fcf39e632ba.png)

**Desktop (please complete the following information):**
 - Version 2.6.15

**Additional context**

**Comment by rlakey** [comment]
Appears to only be an issue with older results files for some reason so closing it.

**Comment by camdenmoors** [comment]
Would you be able to supply the report that caused this issue? Even if it's an older one we want to make sure it works with valid HDF.
