### ISSUE TITLE
Display 'caveat', 'rationale', and 'justification' description fields under test and details tabs

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#297]
We do for our overlays, and instruct others, to define a 'caveat' desc sub-field to explain deviations from standard norms.

This type of field is visible in the code tab, but was supposed to be listed at the top of the details tab and also above the default description of the test tab.
Here above the description, display the 'caveat' information.
![image](https://user-images.githubusercontent.com/34140975/98427205-30116280-206a-11eb-97e8-98c3d3d9b886.png)

Add the 'Caveat', 'rationale', and 'justification' as headings just like 'Desc' currently is.
![image](https://user-images.githubusercontent.com/34140975/98427222-47e8e680-206a-11eb-9711-1da3a2658dfd.png)

AND before the Weakness Description.
![image](https://user-images.githubusercontent.com/34140975/98427687-13762a00-206c-11eb-8edf-d632d395f32f.png)

Background, it already appears here in the code, but we really need it also under the other tabs too:
![image](https://user-images.githubusercontent.com/34140975/98427287-8da5af00-206a-11eb-9b88-0fce1260c88c.png)

**Comment by aaronlippold** [comment]
We need to determine the right place for this https://github.com/mitre/inspecjs/pull/23
