### ISSUE TITLE
Exports in profile view

### ISSUE THREAD

**Issue by Amndeep7** [mitre/heimdall2#3020]
You can export a profile.json as csv or html, but you cannot export one to xccdf or asff (they crash or return empty files).  Exporting as json just returns the original profile.json.

Should all the exporters return valid files (requires modifications to the mappers to support profile jsons and not just hdf files) or should we remove non-functional exporters from that view (i.e. the export as drop down will not contain options for asff/xccdf/etc)?

@ejaronne 

Thanks to @em-c-rod for making me think of the profile view.

**Comment by ejaronne** [comment]
For now, just keep/show the export json choice.
