### ISSUE TITLE
export to ckl does not work with overlays

### ISSUE THREAD

**Issue by Amndeep7** [mitre/heimdall2#3050]
@rlakey reported that HDF files exported to CKL from Heimdall do not display all of the information (such as results and statuses) when opened up in stigviewer.

the reason for this is that the exporter code only looks at the first profile in the list and doesn't know how to handle overlay profiles (i.e. it doesn't look at the profiles that are being overlayed on which is where the results and statuses appear).

https://github.com/mitre/heimdall2/blob/master/apps/frontend/src/components/global/ExportCKLModal.vue#L209

duplication: export rhel7 baseline as ckl from heimdall and see that it works, then export the 3 layer overlay example as ckl and see that it doesn't work.  the overlay dependent on multiple other profiles example from vmware also doesn't work - reach out to me @camdenmoors and I can link it to you.

current workaround is to use inspec_tools' inspec2ckl functionality, which does handle overlays properly.  can probably try to use that code as inspiration for the solution in typescript.

**Comment by rlakey** [comment]
Any updates on fixing this for saf cli and heimdall?

**Comment by camdenmoors** [comment]
> Any updates on fixing this for saf cli and heimdall?

No fixes yet but it has been bumped up in priority, I'll try to get a fix in Tuesday.
