### ISSUE TITLE
E2E GUI Testing Tasks

### ISSUE THREAD

**Issue by rx294** [mitre/heimdall2#31]
- [x] Login (Positive + Negative)
- [x] Registration (Positive + Negative)
- [x] Figure out how to register session without having to go through the login page every time.
- [ ] Upload an evaluation (Once Sam P finishes evaluations)
- [x] Validate the Logout button properly displays
- [x] Validate that Logout button properly removes the session

**Comment by sjoshi10** [comment]
Currently, working on using Page Object Model for the tests that is being written.
