### ISSUE TITLE
[BUG] Is anyone have Running Docker Container issue? got a blank page and error message.

### ISSUE THREAD

**Issue by benaiops** [mitre/heimdall2#3149]
**Describe the bug**
After setup Docker Container, and docker-compose up successfully, but got blank page and "Refused to execute inline script because it violates the following Content Security Policy directive..." error message.

**To Reproduce**
1. Download and setup Docker Container
2. docker-compose up
3. Press F12, got error message on "Console"
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-9doHP5y4UuRcgT3vpfwQ4vEiQ9eY87m+ZSjzIImWAL0='), or a nonce ('nonce-...') is required to enable inline execution.

**Expected behavior**
As a successful installation, there should be a heimdall console on the web.

**Screenshots**
![image](https://user-images.githubusercontent.com/70264393/173383507-eb081c3c-15a0-4af1-b6a8-dbb7b712f2d3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version heimdall2-2.6.26

**Comment by camdenmoors** [comment]
Hi, I am able to reproduce this with the latest release, I'll update when I have further details. Thanks for the heads up

**Comment by camdenmoors** [comment]
If you edit your docker-compose.yml and change `mitre/heimdall2:release-latest` to `mitre/heimdall2:2.6.25` you should be able to use an older version.

**Comment by benaiops** [comment]
Hi Camden, 

 著

   Thank you very much.

 偔

Best regards,

 �

Ben

 �

**Comment by camdenmoors** [comment]
The issue should be fixed now, run `docker compose pull` to pull the latest rebuild.

**Comment by benaiops** [comment]
Hi Camden,

 葖

               Thanks a lot !

 ѓ

Regards,

 쑗

Ben

 ꑗ
