### ISSUE TITLE
[BUG] : AWS S3

### ISSUE THREAD

**Issue by kajalnp** [mitre/heimdall2#3202]
**Describe the bug**
I did complete the add a Cross-Origin Resource Sharing policy within the AWS Console per https://github.com/mitre/heimdall2. Still I am not able to access the AWS S3 bucket. It says "The provided access token is invalid"

**To Reproduce**
1. Go to Hiemdall lite after installation in Cloud One AWS EC2 instance. I am using HTTP (not https). 
2. Click on AWS S3, provide Access Token, Secret Token. Click Basic Login
3. Scroll down to ...

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: AWS Linux
 - Browser : chrome
 - Version [e.g. 26]

**Smartphone (please complete the following information):**

**Additional context**
Running EC2 on Cloud One Zone C

**Comment by Amndeep7** [comment]
@kajalnp I believe we addressed this issue in our pairing session.  For now, I will be closing this issue.  If it comes up again, please re-open this issue.
