### ISSUE TITLE
Update Converters List

### ISSUE THREAD

**Issue by georgedias** [mitre/heimdall2#3507]
**Describe the bug**
Both the lite and server versions have an outdated converters list on the upload modal when hovering over the info icon

**To Reproduce**
1. Start Heimdall (lite or Server)
2. Click on the 'Load' if the load page is not already opened
 
![image](https://user-images.githubusercontent.com/13986875/188021304-09aa03fb-6f6b-4b37-8791-bd5c6d8e89ed.png)

4. Hover over the info icon 
![image](https://user-images.githubusercontent.com/13986875/188021016-b4e76331-5490-4032-8f01-49a89a76c1c8.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/13986875/188020547-5fe36675-8300-46fb-b417-bcbcda6763a0.png)
![image](https://user-images.githubusercontent.com/13986875/188020674-e21f7933-9e96-4095-8ea8-b4d8eaa13703.png)

**Comment by harishfalco** [comment]
Greetings, @georgedias   I'm new to contributing to open-source, I'd want to fix this problem. Give it to me, if possible.
