### ISSUE TITLE
Process group claim from OIDC

### ISSUE THREAD

**Issue by blake-burton** [mitre/heimdall2#3577]
**Is your feature request related to a problem? Please describe.**
Currently OIDC connector does not read in or process the group claim, Looking to have the group claim process and all claim attributes be processed and matched to existing groups inside Heimdall.

**Describe the solution you'd like**
User in Keycloak has 2 groups (G1, G2) those are passed in the group claim. If Heimdall has G1 and G2 created then when the user logs in, they should be part of G1 and G2. fit the user is no longer in the G2 groups and the claim now only container G1, the user should only have access to G1 items.

**Describe alternatives you've considered**
No real alternatives. 

**Desired Impact to Workflow**
Users would not need to log in to then be assigned a groups within the app. Users groups can be passed in from the identity provider.

**Comment by Amndeep7** [comment]
Resolved by https://github.com/mitre/heimdall2/pull/3922
