### ISSUE TITLE
Add option to display legacy Vuln ID

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#3645]
Add a slider option to "Show Legacy ID" to the left of the other sliders on the "Results View Data" band.
When enabled, ADD a column to the right of the current ID column to labeled "Legacy ID" and display (if it exists), the first item in the legacy tag array.

For example, the newer ID SV-204392 was known in older STIGs as V-71849, which is provided in the InSpec profile:

tag 'legacy': ['**V-71849**', 'SV-86473']

This is important so that users of older profiles are not confused to think they have new findings, rather they are just possibly relabeled versions of existing findings.

**Comment by ejaronne** [comment]
Actually, @Amndeep7 had a good suggestion to simplify this, by showing the legacy ID in the same column after the ID. Also, we could take it further and try something like this:

*If* the legacy ID exists for *any* requirement in the HDF(s) loaded, change the column heading from "ID" to "ID [Legacy ID]" and change items in the column accordingly, so:

SV-20439

changes to

SV-20439 [V-71849]

*and* we don't really need to have a toggle at all.  *Much* simpler approach.

If some of the results don't have an ID but no Legacy ID, *don't* show an empty [ ] next to it, of course.

**Comment by Amndeep7** [comment]
After further discussion with @ejaronne 

Column header should just be "ID", but add a tooltip that people can hover that can explain the format of what the column value will look like and also what it means for there to be legacy ids in the first place.

Column value should look like

```
SV-20439
(V-71849)
```

Note the newline between the actual id and the legacy id.  Note the parantheses around the legacy id.  Note that it is only ever going to be a single legacy id that gets listed no matter how many there actually are out there.

**Comment by ejaronne** [comment]
[rhel8_stig_baseline_10122022.json.txt](https://github.com/mitre/heimdall2/files/9842808/rhel8_stig_baseline_10122022.json.txt)
Sample file for testing

**Comment by ejaronne** [comment]
"controls": [
				{
					"id": "SV-204392",
					"title": "The Red Hat Enterprise Linux operating system must be configured so that the file permissions, ownership,\n    and group membership of system files and commands match the vendor values.",
					"desc": "Discretionary access control is weakened if a user or group has access permissions to system files and\n    directories greater than the default.",
					"descriptions": [
						{
							"label": "default",
							"data": "Discretionary access control is weakened if a user or group has access permissions to system files and\n    directories greater than the default."
						},
						{
							"label": "rationale",
							"data": ""
						},
						{
							"label": "check",
							"data": "Verify the file permissions, ownership, and group membership of system files and commands match the\n    vendor values.\n    Check the default file permissions, ownership, and group membership of system files and commands with the following\n    command:\n    # for i in `rpm -Va | egrep '^.{1}M|^.{5}U|^.{6}G' | cut -d \" \" -f 4,5`;do for j in `rpm -qf $i`;do rpm -ql $j\n    --dump | cut -d \" \" -f 1,5,6,7 | grep $i;done;done\n    /var/log/gdm 040755 root root\n    /etc/audisp/audisp-remote.conf 0100640 root root\n    /usr/bin/passwd 0104755 root root\n    For each file returned, verify the current permissions, ownership, and group membership:\n    # ls -la <filename>\n    -rw-------. 1 root root 133 Jan 11 13:25 /etc/audisp/audisp-remote.conf\n    If the file is more permissive than the default permissions, this is a finding.\n    If the file is not owned by the default owner and is not documented with the Information System Security Officer\n    (ISSO), this is a finding.\n    If the file is not a member of the default group and is not documented with the Information System Security Officer\n    (ISSO), this is a finding."
						},
						{
							"label": "fix",
							"data": "Run the following command to determine which package owns the file:\n\n    # rpm -qf <filename>\n\n    Reset the user and group ownership of files within a package with the\nfollowing command:\n\n    #rpm --setugids <packagename>\n\n\n    Reset the permissions of files within a package with the following command:\n\n    #rpm --setperms <packagename>"
						}
					],
					"impact": 0.7,
					"refs": [],
					"tags": {
						"legacy": [
							"V-71849",
							"SV-86473"
						],
