### ISSUE TITLE
Create Update Workflow

### ISSUE THREAD

**Issue by camdenmoors** [mitre/heimdall2#374]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For the backend to check for new releases from [here](https://api.github.com/repos/mitre/heimdall2/releases/latest). Only admin users will be able to update.

**Describe alternatives you've considered**
None

**Desired Impact to Workflow**
Checks for updates on launch and will prompt the user to update (perhaps using a snackbar).

Requested by @aaronlippold

**Comment by rbclark** [comment]
@aaronlippold can you provide clarification on what exactly this is? Users will be notified that there is an upgrade by https://github.com/mitre/heimdall2/pull/468 and for users running docker upgrading is just a matter of running

```
docker-compose pull
docker-compose restart
```

**Comment by aaronlippold** [comment]
I think I mean the tool that helps them upgrade from Heimdall 1 to 2 -
connect, migrate, etc dbs, users, data etc from HS1.0 to HS2.0.
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by aaronlippold** [comment]
live update in place would be cool as well :)
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
