### ISSUE TITLE
Group Search / Filter

### ISSUE THREAD

**Issue by em-c-rod** [mitre/heimdall2#3789]
- [ ] Allow results to be filtered by group and tag. For example, if User A is a part of Group I and Group II, then add a filter on results to see all results in Group II.

**Comment by ejaronne** [comment]
![image](https://user-images.githubusercontent.com/34140975/204620818-0b4f383c-65c1-4432-9e01-f69867fc81b0.png)
This is all I wanted for initial release by next week if possible

**Comment by Rlin232** [comment]
Resolved by #3790
