### ISSUE TITLE
Stand up GraphQL/REST DB to serve NIST and CMS control descriptions.

### ISSUE THREAD

**Issue by Mitriol** [mitre/heimdall2#38]
Resolves short term feature fix mitre/heimdall-lite#116. Standard files are big - to improve user experience, and minimize bandwidth waste, we should send as little data as is necessary (only really need the controls the user is trying to view). Request this data asynchronously via graphql, send back the relevant controls. Locally cache the ones that have been sent (not literally in the cache, just in memory).

**Comment by Bialogs** [comment]
It's probably useless to do this because these features need to work in heimdall-lite when not in server mode.

**Comment by rbclark** [comment]
This also goes in a very different direction from what @ejaronne has been requesting, a lot of his complaints have been around the frontend trying to be too 'smart' in it's loading of items (for example when trying to print the fact that a bunch of white pages are shown instead of actual results).
