### ISSUE TITLE
Change Comparison View to a toggle switch instead of a button

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall2#384]
The navigation back to the results view seems to be broken once you go into the compare view. This makes it so I have to click on the Profile view then back on the Results view to get back.

Options for fixing (in order of preference):

1. Add a toggle switch next to the Comparison view button and show it in the correct state.
1. Rename the button to <Switch to Comparison View> when results view is active, and <Switch to Results View> when comparison view is active.

**Comment by rbclark** [comment]
Are you saying that switching from Comparison view to Profile view and then back to Results view should return to Comparison view and not Results view?

![output](https://user-images.githubusercontent.com/2308869/97176189-f6d41b00-176a-11eb-86d6-626d12eb0bb6.gif)

**Comment by Amndeep7** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/2015821/100293093-92b29b80-2f50-11eb-88b3-a92f86e96895.png">

Does this roughly match what you're going for?  Gotta muck with the css to make it match the look/feel.

Also does the label being "Comparison View: enabled/disabled" work or do you want that text changed?

@aaronlippold @rbclark

**Comment by rbclark** [comment]
@Amndeep7 I was envisioning getting rid of the icon and just showing the toggle in place of it. I think the active or inactive toggle is enough, no need to show the "enabled" or "disabled" text next to it.
