### ISSUE TITLE
Filter view of selected results by name/tag/group

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#3857]
Initial feature:
Extend the default search bar to filter the view of **selected** results by full/partial filename, associated tag or group:
![image](https://user-images.githubusercontent.com/34140975/232501709-6a98d11d-1f97-4d98-b56a-b676963be09e.png)

This filter should work *within* the context of the files selected for display in the left-side menu. The search bar items should *not* compete with nor try to reflect the checked files in the left-side menu.

**Comment by samcornwell** [comment]
#4471

**Comment by samcornwell** [comment]
completed with #4397
