### ISSUE TITLE
[BUG] Profiles that are loaded in at the same time as results cause a type error

### ISSUE THREAD

**Issue by Amndeep7** [mitre/heimdall2#3902]
**Describe the bug**
When a profile and results file are loaded in at the same time, a type error appears at delta_util:

![image](https://user-images.githubusercontent.com/2015821/209900937-a1ce802e-4748-477e-873d-ca1fa6cbc74a.png)

Causes at least the following issues:
- 'display only changed results' button in the comparison view doesn't do anything

**To Reproduce**
1. Load one or more results files
2. Load a profile
3. See error pop up in terminal
4. (Optional) Go to comparison view and see how bits and pieces of the UI don't work

**Expected behavior**
The comparison view works properly / there's no type error

**Screenshots**

Before loading the profile:

![image](https://user-images.githubusercontent.com/2015821/209901313-0274d233-2089-491a-bafa-86597029869e.png)

After loading the profile:

![image](https://user-images.githubusercontent.com/2015821/209901360-905d96ed-e0b5-4383-91e6-8631dafdaba5.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 108.0

**Additional context**
If you could also submit the file that would also be great!

**Comment by ChrisHinchey** [comment]
This also holds true when the checklist PR is added into master
