### ISSUE TITLE
Teams Management

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#3924]
- [ ] Since Groups in our context relates to groupings of people, change the term to “Teams” to distinguish from mere tags/labels applied to result data. 
(Our tags are labels applied to data sets, in our case, primarily “result sets” in HDF form in the database.)

- [ ] Create a “Teams” management page/modal very similar to Github’s teams/sub-teams management feature: [https://github.com/orgs/mitre/teams](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Forgs%2Fmitre%2Fteams&data=05%7C01%7CRaja.Krishnamurthy%40ventechsolutions.com%7C6cc27eb56bf94736b04108daea81be34%7Ca2ac7cb65f0c4763a2121e2c42e334e5%7C0%7C0%7C638080141119295156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2XF7Nv087praD5qDG2Kit72Qkn87HpmFQkIaiUxg1JQ%3D&reserved=0), [https://docs.github.com/en/organizations/organizing-members-into-teams/about-teams](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.github.com%2Fen%2Forganizations%2Forganizing-members-into-teams%2Fabout-teams&data=05%7C01%7CRaja.Krishnamurthy%40ventechsolutions.com%7C6cc27eb56bf94736b04108daea81be34%7Ca2ac7cb65f0c4763a2121e2c42e334e5%7C0%7C0%7C638080141119295156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qGHOHZNFpSJ3Q6EOk8jFz8La5U6MdqLncwaV11Vqm1U%3D&reserved=0) 

- [ ] On the database load modal and loaded results list menu, enhance search to do multi-value “AND” searches of any combination of Teams, Tags, filename

**Comment by Rlin232** [comment]
This is addressed by
1. N/A
2. https://github.com/mitre/heimdall2/issues/4707
3. https://github.com/mitre/heimdall2/issues/3857
respectively
