### ISSUE TITLE
[BUG] Inspec Profile view should use Severity instead of Impact for Results View Data

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#399]
**Describe the bug**

**To Reproduce**
1. Load the attached json [output.txt](https://github.com/mitre/heimdall2/files/5453259/output.txt)
2. Search for `V-58157`
2. Notice that the severity shows as None. This is due to the way that the inspec json command parses profiles when generating a `profile.json`. 
3. Go to the `Code` tab for this control.
4. See that the impact is in fact what is being displayed (which does not work properly on profile.json files).

**Expected behavior**
The `tag "severity": "medium"` should instead be what is displayed for profiles, and impact should be displayed for results.

**Screenshots**
<img width="1197" alt="Screen Shot 2020-10-28 at 12 14 10 PM" src="https://user-images.githubusercontent.com/2308869/97464287-18720580-1917-11eb-87fe-0f569d22e623.png">

<img width="1034" alt="Screen Shot 2020-10-28 at 12 14 38 PM" src="https://user-images.githubusercontent.com/2308869/97464322-27f14e80-1917-11eb-8519-d0b8a53c1929.png">

**Comment by ejaronne** [comment]
Seems to work thanks!
