### ISSUE TITLE
[BUG] Release 2.6.38 has a typescript compilation issue

### ISSUE THREAD

**Issue by marc90s** [mitre/heimdall2#4064]
**Describe the bug**

Upon running docker compose up -d withing the heimdall2 directory. Container 98d1fb4c83c5 exits after attempting to restart.

CONTAINER ID | IMAGE | COMMAND | CREATED | STATUS | PORTS | NAMES
-- | -- | -- | -- | -- | -- | --
c30db141c116 | nginx:alpine | "/docker-entrypoint.…" | 11 minutes ago | Up 11 minutes | 0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp,   :::443->443/tcp | heimdall2-nginx-1
98d1fb4c83c5 | mitre/heimdall2:release-latest | "docker-entrypoint.s…" | 11 minutes ago | Exited (1) 6 minutes ago | heimdall2-server-1
c45e960941a4 | postgres:13 | "docker-entrypoint.s…" | 11 minutes ago | Up 11 minutes | 5432/tcp | heimdall2-database-1

--------------------------------------------------------------------------------------------
```
docker logs 98d1fb4c83c5

Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.19/lib/cli.js sequelize-cli db:migrate
Directory: /app/apps/backend
Output:

error Command failed with exit code 1.
ERROR: Error reading "db/database.ts". Error: TSError: ⨯ Unable to compile TypeScript:
config/app_config.ts(14,11): error TS2571: Object is of type 'unknown'.

error Command failed with exit code 1.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.19/lib/cli.js sequelize-cli db:migrate
Directory: /app/apps/backend
Output:

error Command failed with exit code 1.
ERROR: Error reading "db/database.ts". Error: TSError: ⨯ Unable to compile TypeScript:
config/app_config.ts(14,11): error TS2571: Object is of type 'unknown'.

error Command failed with exit code 1.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.19/lib/cli.js sequelize-cli db:migrate
Directory: /app/apps/backend
Output:

error Command failed with exit code 1.
$ yarn workspace heimdall-server sequelize-cli db:migrate
$ ts-node --esm node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 16.19.0, CLI: 6.6.0, ORM: 6.28.0]
```

**To Reproduce**

Run the sequelize-cli commands (ex. by doing a docker-compose up)

**Expected behavior**

The compilation to succeed, the db migration scripts to run, and the containers successfully booted

**Comment by Amndeep7** [comment]
Thanks @marc90s and @rlakey for pointing this out.  We did a bunch of dependency updates at once and thought we'd caught all the issues, but might've missed testing the release from a docker container before pushing it out.  That's on us.  We'll try to have this resolved asap.

**Comment by Amndeep7** [comment]
@marc90s @rlakey please try using 'latest' (not 'release-latest') in the dockerfile / helm chart / wherever you're running Heimdall to see if it fixes it in your environments.  'release-latest' will be updated on our next release which will be on this upcoming monday or tuesday.
