### ISSUE TITLE
Unable to load Inspec Results file - no logs/error messages

### ISSUE THREAD

**Issue by kclinden** [mitre/heimdall2#407]
When trying to import my Inspec Results file it fails, but it doesn't not give me a meaningful error. I have tried this with the Netlify and a locally hosted version of Heimdall 2.

**To Reproduce**
1. Import attached results file which is based off of the Windows 2016 STIG Inspec Profile

**Expected behavior**
Results will be imported and work

**Screenshots**
![image](https://user-images.githubusercontent.com/7460412/97499330-b2e44000-193b-11eb-9dab-05eb14d54067.png)

**Additional context**
Attached results file.
[results.json.zip](https://github.com/mitre/heimdall2/files/5454941/results.json.zip)

**Comment by aaronlippold** [comment]
Added @Mitriol in case this was an inspecjs thing

**Comment by rbclark** [comment]
This is now fixed in the netlify preview and will be included in the release of `2.3.3` next Friday.
