### ISSUE TITLE
Bucket 'Waived' Controls as Waived as we do for 'Profile Errors' 

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall2#410]
Using the HDF backend, filter the controls array base on the waived boolean prop and bucket and filter any controls that have been Waived as such rather than putting them as Not Applicable.

Not Applicable is a different business decision so I want to clearly distinguish between the two if an end user chooses to Waive controls.

**Comment by rbclark** [comment]
@ejaronne I would like to get concurrence from you and @aaronlippold on this issue before we go and implement this since I believe you have a different opinion on this one.

**Comment by ejaronne** [comment]
@rbclark please help me see how waiver tests are currently handled in inspecjs and heimdall. I can't find the section of code for that.

**Comment by aaronlippold** [comment]
Hi,

What I want is simple, when we have data in the result set that is marked
as 'waived' I want to have a notice that there are waived controls - which
I will also want for attested data - just like we do with 'error data' - so
I can easily sort on or filter and review our 'special class' data types.
Thee data types are outside our 'buckets' of passed, failed, skipped, and
NA. They are a sub-set of the data - which have known conditions - that
push them out of the 4 standard accepted states.

Thanks,

Aaron
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by rbclark** [comment]
After speaking to @aaronlippold and @ejaronne, it has been decided that this should be implemented exactly the same as Profile Errors. The 4 buckets along the top should still be Passed, Failed, Not Applicable, and Not Reviewed:

<img width="1521" alt="Screen Shot 2020-12-01 at 12 25 52 PM" src="https://user-images.githubusercontent.com/2308869/100774700-5bb90b80-33d0-11eb-952d-df0dd6935665.png">

The Compliance graph should include Waived controls in the denominator:
`[Passed/(Passed + Failed + Not Reviewed + Profile Error) * 100]` should be `[Passed/(Passed + Failed + Not Reviewed + Profile Error + Waived) * 100]`

Waived controls should be added to the `Status Counts` donut chart.

And a bar should be added similar to the one that currently exists for Profile Errors, only it should say
<img width="1396" alt="Screen Shot 2020-12-01 at 12 37 12 PM" src="https://user-images.githubusercontent.com/2308869/100775962-f239fc80-33d1-11eb-9160-f36ecd0d499f.png">

**Comment by rx294** [comment]
Attaching Inspec results JSON when waiver is used as per @rbclark request.

Results Without waiver: apache2-server-orig-sample.json
Results With waiver: apache2-server-waiver-sample.json

Waiver file used : waiver.yml


[waiver.zip](https://github.com/mitre/heimdall2/files/5705936/waiver.zip)
