### ISSUE TITLE
Manage group ownership properly during different group owner change cases

### ISSUE THREAD

**Issue by Rlin232** [mitre/heimdall2#4196]
Currently, Heimdall does not properly handle the case of what to do when all owners are removed. A proposed system is to make the default admin the owner of the "abandoned" group.

**Comment by Amndeep7** [comment]
From @aaronlippold: for the GUI, allow the last owner to specify who the new owner can be if they try to remove themselves as the owner.  The default will be the default admin.

**Comment by ejaronne** [comment]
Case 1: owner attempts to bump oneself to member. warning pops up to promote/add at least one other as owner.
Case 2: owner promotes/adds at least one other as owner. owner demotes self to member. modal auto-saves and closes. group is show on my groups but no longer editable.
Case 3: owner promotes/adds at least one other as owner. owner deletes self to member. modal auto-saves and closes. group is no longer shown on my groups.
Case 4: server admin deletes user. user is owner of one or more groups. for any group that doesn't currently have a secondary owner, set the owner to the default admin.
