### ISSUE TITLE
Add None to the Severity Counts Summary

### ISSUE THREAD

**Issue by em-c-rod** [mitre/heimdall2#4734]
The Status Counts and Severity Counts totals can show up differently when there are controls with no severity (e.g. Not Applicable). Can the none category be added to severity so the total count still reflects the total number of controls from the guidance?

Steps to reproduce the error:
1. Go to Heimdall Lite
2. Load the Red Hat 7 STIG Baseline sample report
3. View the results (Status count = 243, Severity Count = 233)

**Comment by Amndeep7** [comment]
This issue will be resolved when the following locations are fixed

- [ ] HTML export also has 'none' severity support (@charleshu-8)
- [ ] Checklist viewer PR has 'none' severity support (@ChrisHinchey)
- [x] Current master has 'none' severity support

**Comment by ChrisHinchey** [comment]
@Amndeep7 After rebasing it looks like the 'none' severity support is in the checklist viewer 
![image](https://github.com/mitre/heimdall2/assets/112198118/4b3ec8e7-8dbd-4fef-bfd3-6ed472a54fba)
