### ISSUE TITLE
Add Gravatar support to Heimdall Profile

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall2#481]
https://en.gravatar.com/site/implement/profiles/jsapi/

**Comment by rbclark** [comment]
@aaronlippold is this a critical issue that we need in the 2.3.5 milestone or can we bump it back into the backlog so that we can focus on other issues?

**Comment by aaronlippold** [comment]
I thought it was a small thing we could push into the user model as it
seemed to be logically in scope. If it is less then just adding a working
component from npm and adding it to our component then we can move it to
the backlog. But I assumed it was a working thing someone had already
worked out.

e.g : https://github.com/JiriChara/vue-gravatar
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by rbclark** [comment]
It's not necessarily difficult, it just may take a little bit of time to get it to look how we want it to (I don't see obvious reference off the bat for rounding the corners for example). It may be best to leave this in the backlog for now and deal with it when we get further down the road.
