### ISSUE TITLE
Enable HTML rendering in the `Test Details` tag

### ISSUE THREAD

**Issue by rx294** [mitre/heimdall2#482]
Please enable HTML rendering in the `Test Details` tag

This especially  meaningful for heimdall tools json view

H-Lite view

![image](https://user-images.githubusercontent.com/17052944/65726543-569d5580-e083-11e9-97ce-66337dc2f56d.png)

Current Heimdall view
![image](https://user-images.githubusercontent.com/17052944/65726568-64eb7180-e083-11e9-80de-941b9b16b399.png)

**Comment by rbclark** [comment]
As a note on this, it will require adding some sort of text clamping back to avoid the Test tab getting crazy long
