### ISSUE TITLE
Add documentation for db schema

### ISSUE THREAD

**Issue by Amndeep7** [mitre/heimdall2#4961]
We do not currently have a formal database schema published for Heimdall – we’ve been using Sequelize migrations/classes to set up the DB.
 
I’m attaching a dump of the schema from the latest release as well as a draw.io representation of it.  You can replicate my process as follows:
 
Spin up the service in docker: `docker compose pull` -> `docker compose up`
Identify the postgres container: `docker ps | grep postgres | awk '{ print $1 }'` (was bb50fb86f0b8 for me)
Dump the schema from the db: `docker exec -it -u postgres bb50fb86f0b8 sh -c "pg_dump -s heimdall-server-production > /tmp/heimdall_dump.sql"`
Extract the schema from the container: `docker cp bb50fb86f0b8:/tmp/heimdall_dump.sql heimdall_dump.sql`
(Optionally) Use draw.io to visualize the schema: https://softwarerecs.stackexchange.com/a/83974/684
![Untitled Diagram drawio](https://github.com/mitre/heimdall2/assets/2015821/af340d6e-f974-46b7-a4cb-d9e99b1806c3)
[heimdall_dump.sql.txt](https://github.com/mitre/heimdall2/files/12652158/heimdall_dump.sql.txt)

**Comment by aaronlippold** [comment]
﻿https://www.npmjs.com/package/sequelize-erd <https://www.npmjs.com/package/sequelize-erd> 

May be useful or some other project in the same vain. 

May also be a good thing for us to add to the release process as we update versions. 

Respectfully, 
-------------------- 
Aaron Lippold 
Chief Engineer – MITRE Security Automation Framework (SAF) 
https://saf.mitre.org <https://saf.mitre.org/> 
Principal Cyber Security Engineer 

571-384-9233 
***@***.*** ***@***.***> 




From: Amndeep Singh Mann ***@***.***>
Date: Monday, September 18, 2023 at 14:39
To: mitre/heimdall2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXT] [mitre/heimdall2] Add documentation for db schema (Issue #4961) 

We do not currently have a formal database schema published for Heimdall – we’ve been using Sequelize migrations/classes to set up the DB. I’m attaching a dump of the schema from the latest release as well as a draw. io representation of it. 

 

We do not currently have a formal database schema published for Heimdall – we’ve been using Sequelize migrations/classes to set up the DB. 
I’m attaching a dump of the schema from the latest release as well as a draw.io representation of it. You can replicate my process as follows: 
Spin up the service in docker: docker compose pull -> docker compose up
Identify the postgres container: docker ps | grep postgres | awk '{ print $1 }' (was bb50fb86f0b8 for me)
Dump the schema from the db: docker exec -it -u postgres bb50fb86f0b8 sh -c "pg_dump -s heimdall-server-production > /tmp/heimdall_dump.sql"
Extract the schema from the container: docker cp bb50fb86f0b8:/tmp/heimdall_dump.sql heimdall_dump.sql
(Optionally) Use draw.io to visualize the schema: https://softwarerecs.stackexchange.com/a/83974/684 <https://softwarerecs.stackexchange.com/a/83974/684>
<_blank>
heimdall_dump.sql.txt <https://github.com/mitre/heimdall2/files/12652158/heimdall_dump.sql.txt>

**Comment by georgedias** [comment]
We have added a [database sql script](https://github.com/mitre/heimdall2/blob/master/apps/backend/db/heimdall_database_script.sql) that generates the Heimdall database tables, relationships, indexes, and procedures.

An Entity Resolution Diagram (ERD) for the database is found in this [wiki page](https://github.com/mitre/heimdall2/wiki/Heimdall-Class-Diagrams)
