### ISSUE TITLE
expand search to include all desc fields, tags, code, results and search on multiple items at once

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#524]
Search seems to be limited to certain fields. Users creating overlays, for instance, may add additional sub-descriptions. Can we make the search cover any part of the test, details, or code text?

Can it also search multiple strings, quoted phrases, and do things like OR and AND?

**Comment by rbclark** [comment]
To reproduce this, load the `Triple Overlay Example` and search for any of the Caveat data in `V-61749`.
