### ISSUE TITLE
ERROR message incorrectly shows for overlay profile results

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#5418]
Probably introduced during PR https://github.com/mitre/heimdall2/pull/5298 

It is incorrectly casting the ERROR message for items in overlays. It is probably seeing the "results": [] that appears in the additional profile objects that show up in an overlay profile result set. However, all actual results are consolidated in baseline profile object! Can be seen in built in samples:

![image](https://github.com/mitre/heimdall2/assets/34140975/16c30b73-636f-4af2-b883-1ef2696292ee)

![image](https://github.com/mitre/heimdall2/assets/34140975/48bd155b-7477-456b-9624-c7a0da779d93)

![image](https://github.com/mitre/heimdall2/assets/34140975/a037e393-baf5-4fcc-95c4-9a17c329aced)

![image](https://github.com/mitre/heimdall2/assets/34140975/c1523354-52d6-44a5-8bb0-ab0260b00b0e)

![image](https://github.com/mitre/heimdall2/assets/34140975/294c8b9a-72e1-4aff-8263-0428b6c65424)

**Comment by aaronlippold** [comment]
My thought is that the processing isn't happening in the right place. We have a finalized processed object in inspect JS that should derive everything down to a single set of controls if I remember correctly or more directly a single set of results for that control or overlaid control, it's that objective I recall that we need to be looking at so maybe we can explore that a bit.
