### ISSUE TITLE
Add STIG name, version, and classification on export to checklist

### ISSUE THREAD

**Issue by em-c-rod** [mitre/heimdall2#5554]
After exporting HDF results to a checklist in Heimdall, the name that appears on the checklist when loaded in STIG Viewer is the profile name instead of the STIG name and STIG version. It also doesn't have the classification listed.

Current example:
<img width="566" alt="Screenshot 2024-02-16 at 9 58 19 AM" src="https://github.com/mitre/heimdall2/assets/32680215/15ac0404-b15d-4999-93d6-8f3cd32304f0">

Desired state:
<img width="819" alt="Screenshot 2024-02-16 at 9 58 57 AM" src="https://github.com/mitre/heimdall2/assets/32680215/0e16cba9-d150-4e32-96ef-88078c264971">

Proposed Solution:
In Export to Checklist GUI in Heimdall, add a field for what the title should be. Or add a field for the official STIG name and STIG version. TBD on the classification.
<img width="1413" alt="Screenshot 2024-02-16 at 10 12 06 AM" src="https://github.com/mitre/heimdall2/assets/32680215/12e0f67d-4b5e-47f3-b2a5-df002d826f07">

I think the STIGRef needs to be overwritten with the User Input.
https://github.com/mitre/heimdall2/blob/41a24da3220936fb93ec86bd5ea0830f0ca2a6ac/apps/frontend/public/static/export/cklExport.ckl#L156

Additionally, either consider adding this or make a new issue if not addressed here:
- Add info icons or text for the user to understand what is expected in each field.

For example, 
Info icon:
![Image](https://github.com/mitre/heimdall2/assets/32680215/70a8131c-4900-4cb4-a656-fa346521fe55)
Text Box Below Input for clarification:

![Image](https://github.com/mitre/heimdall2/assets/32680215/34359904-1350-40fe-b531-8ae572b75ded)

**Comment by Amndeep7** [comment]
The structure is there to more or less match the expected output; however, the inputs are often not what is needed to make that happen.  Add some more UI so that the user can overwrite the profile name, but try to provide default values so that the user can see what it is atm.  Same for version/release.
