### ISSUE TITLE
Improve administrator user creation functionality

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#564]
**Is your feature request related to a problem? Please describe.**
There is a button to create users in the admin panel however it is not very visible (it is just a small + in the top right corner). Also when admins do add users the page doesn't automatically refresh with the new users.

**Describe the solution you'd like**
A button that says "Add New User" and an automatically refreshing list after an admin adds a new user.

**Comment by samuelsunvold** [comment]
Update [here](ff9b79cf2a6c2d18c7ab29294fb6782dd3f82892)
