### ISSUE TITLE
complete overlay code view in comparison mode

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#581]
For overlayed controls, the compare view's code view does not show the overlay code "stacked" over the baseline code the same way it does in the results view. For example, load the triple overlay sample and look at V-61409 and V-61441.

**Comment by rbclark** [comment]
For reference:

Control in results view:
<img width="917" alt="Screen Shot 2020-12-03 at 8 58 54 AM" src="https://user-images.githubusercontent.com/2308869/101027182-c770b500-3545-11eb-81c6-00dd8bd3e4ba.png">

Same control in Compare view:
<img width="1535" alt="Screen Shot 2020-12-03 at 8 59 25 AM" src="https://user-images.githubusercontent.com/2308869/101027304-dbb4b200-3545-11eb-89cd-3eb075f9496f.png">

**Comment by camdenmoors** [comment]
Closing because the compare view supports overlayed controls now.

![image](https://user-images.githubusercontent.com/66680985/121076525-85e6ee00-c7a4-11eb-8375-adda0a3f10ef.png)
