### ISSUE TITLE
Summary CAAT report

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#59]
A Summary version of the CAAT, listing only one row for each NIST SP 800-53 security control.
A template/mockup is attached:
[Summary_CAAT_Template_02062020a.xlsx](https://github.com/mitre/heimdall-lite/files/4163382/Summary_CAAT_Template_02062020a.xlsx)
And add menu item as shown:
![image](https://user-images.githubusercontent.com/34140975/73909001-6458b800-4879-11ea-9ac6-d74bdf99f4b5.png)

**Comment by rbclark** [comment]
@ejaronne is this issue still something you are looking for?

**Comment by Amndeep7** [comment]
@ejaronne I'm gonna close this issue.  Please re-open if this is still something you want.
