### ISSUE TITLE
Add Inputs Display to the Profile and Results Views

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall2#598]
Now that our profiles can support `sensitive` inputs - we should render the profile input keys and values in the Heimdall UX.

This would be very useful when I am talking to end-users about overlays, inputs in general, and doing walkthroughs.

As an end-user, for a run, I would like to see all the inputs and their values for that scan, and I would also like to be able to filter my results or controls by their use of inputs.

In profiles that have parent and child profiles, it would be very useful to know, if possible, in which profile or dependency the value of the input came from.

**Comment by ejaronne** [comment]
dependent on https://github.com/mitre/mitre-saf/projects/1 completion before release.

**Comment by rbclark** [comment]
Add a second tab to the Profile Info dropdown, `Profile Information | Inputs`
