### ISSUE TITLE
[BUG] Build for tag v.2.3.5 for production fails on load

### ISSUE THREAD

**Issue by daviddahl** [mitre/heimdall2#619]
**Describe the bug**
I have built tag v2.3.5 of `heimdall-lite` and deployed to Gitlab Pages

~The site is very slow to load~ ... the following errors are displayed in the console:

```
chunk-vendors.023c675c.js:formatted:91236 RangeError: Maximum call stack size exceeded
    at RegExp.get global [as global] (<anonymous>)
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (<anonymous>)
    at me (chunk-vendors.023c675c.js:formatted:72088)
    at o (chunk-vendors.023c675c.js:formatted:72020)
    at l (chunk-vendors.023c675c.js:formatted:72056)
    at u (chunk-vendors.023c675c.js:formatted:72080)
    at o (chunk-vendors.023c675c.js:formatted:72021)
    at l (chunk-vendors.023c675c.js:formatted:72056)
    at u (chunk-vendors.023c675c.js:formatted:72080)
at @ chunk-vendors.023c675c.js:formatted:91236
rt @ chunk-vendors.023c675c.js:formatted:91231
tt @ chunk-vendors.023c675c.js:formatted:91205
nt @ chunk-vendors.023c675c.js:formatted:91220
Dn @ chunk-vendors.023c675c.js:formatted:92253
e._init @ chunk-vendors.023c675c.js:formatted:92606
_r @ chunk-vendors.023c675c.js:formatted:92650
cd49 @ main.ts:16
s @ bootstrap:79
2 @ app.420bec7e.js:1
s @ bootstrap:79
t @ bootstrap:45
(anonymous) @ bootstrap:152
(anonymous) @ app.420bec7e.js:1
chunk-vendors.023c675c.js:formatted:91236 TypeError: Cannot read property 'fullPath' of undefined
    at s.n (App.vue?7f23:1)
    at s.e._render (chunk-vendors.023c675c.js:formatted:91924)
    at s.r (chunk-vendors.023c675c.js:formatted:92177)
    at nr.get (chunk-vendors.023c675c.js:formatted:92358)
    at new nr (chunk-vendors.023c675c.js:formatted:92351)
    at Mn (chunk-vendors.023c675c.js:formatted:92180)
    at s._r.$mount (chunk-vendors.023c675c.js:formatted:94258)
    at init (chunk-vendors.023c675c.js:formatted:91756)
    at p (chunk-vendors.023c675c.js:formatted:93091)
    at f (chunk-vendors.023c675c.js:formatted:93074)
```
**To Reproduce**
1. Run the build steps in the Dockerfile.lite file 
2. Deploy to web server, load the index page
3. No site is rendered, errors above in console

**Expected behavior**
Expectation was the frontend site would load
 
**Screenshots**
<img width="1676" alt="Screen Shot 2020-12-09 at 15 39 53" src="https://user-images.githubusercontent.com/23880/101684731-dcad7e00-3a34-11eb-8137-992c421306df.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.7
 - Browser chrome
 - Version 87.0

**Additional context**
Built inside docker in gitlab using the commands and image in Dockerfile.lite

**Comment by daviddahl** [comment]
I think I may have done the build incorrectly after all, closing for now.

**Comment by daviddahl** [comment]
Re-opening as I have re-built 2 X from the v2.3.5 release tag and still see the same exact error

**Comment by daviddahl** [comment]
BTW, `yarn start:dev` does work

**Comment by rbclark** [comment]
Could you verify how you are building the container? I built using `e7c475c` which is the hash for 2.3.5 using the first command to build and second to start 
    
    docker build -t heimdall-lite:test-235 -f Dockerfile.lite .
    docker run -d -p 8080:80 heimdall-lite:test-235

And was able to build and run 2.3.5 successfully.

I also tested after cloning by running `yarn frontend build` and `python -m SimpleHTTPServer /dist/frontend` and the app worked fine that way as well.

Just to clarify did you attempt to build the container or just use the steps form it?

**Comment by daviddahl** [comment]
From what I can tell from the minimized code, this function is being called a bunch of times: https://github.com/vuejs/vue-router/blob/dev/dist/vue-router.js#L1682

Is that something to do with the full server version of heimdall2? I don't see why the lite version would have so many routes.

**Comment by rbclark** [comment]
We have a Github Action for building the application that runs on every release to deploy https://heimdall-demo.mitre.org, https://github.com/mitre/heimdall2/blob/master/.github/workflows/gh-pages.yml, if that helps.

**Comment by daviddahl** [comment]
FWIW, I made a debugging session video here: https://imgur.com/a/iaoYsJp

**Comment by daviddahl** [comment]
@rbclark I am doing the same things as the GA workflow, just did not know about adding the CNAME file to the `dist/frontend` dir

**Comment by rbclark** [comment]
That points to the CNAME as a strong possible culprit, did that end up helping with your deployment?

**Comment by daviddahl** [comment]
> That points to the CNAME as a strong possible culprit, did that end up helping with your deployment?

I do think I have some kind of internal networking issue, but, the ` RangeError: Maximum call stack size exceeded` error still stands on a local build on macOS

**Comment by rbclark** [comment]
What server are you running with locally? I'm still not having any issues running with the basic use case of `yarn frontend build` and `cd dist/frontend; python -m SimpleHTTPServer` locally which is making it difficult to reproduce your issue.

**Comment by daviddahl** [comment]
I am running nginx and I think it has to do with the path at which the app is being served. I have just confirmed this. If you want to run heimdall-lite at `/my-project/my-heimdall/' (as it would be in Gitlab Pages) it just will not load. It expects the app to be served from `/`.

**Comment by daviddahl** [comment]
If you run `python3 -m http.server 9000` in `/` and open `localhost:9000/dist/frontend` you will only see the brown background and mitre copyright and the `RangeError: Maximum call stack size exceeded` kills the load.

**Comment by rbclark** [comment]
That sounds right, we always serve heimdall-lite off of the root directory, the router is the spot where your error is happening, not the vue config. The command you provided works fine with the following change:

```
diff --git a/apps/frontend/src/router.ts b/apps/frontend/src/router.ts
index 78942724..2d007b02 100644
--- a/apps/frontend/src/router.ts
+++ b/apps/frontend/src/router.ts
@@ -12,6 +12,7 @@ import Router from 'vue-router';
 Vue.use(Router);
 
 const router = new Router({
+  base: '/dist/frontend',
   mode: 'history',
   routes: [
     {
```

**Comment by daviddahl** [comment]
Thank you - I am quite ignorant of Vue in practice. I will test this later today. Cheers.

**Comment by rbclark** [comment]
Just wanted to check and make sure this issue was resolved?

**Comment by daviddahl** [comment]
Yes, sorry. I'll close it  - resolved.
