### ISSUE TITLE
Redesign sidebar to include Results + Profiles

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#69]
Depends on mitre/heimdall2#65

This is how the sidebar is currently displayed when a user loads a Result and Profile:

<img width="375" alt="Screen Shot 2020-08-19 at 7 32 48 PM" src="https://user-images.githubusercontent.com/2308869/90700087-e4ad9c00-e252-11ea-8e09-5a64397d639b.png">

This has 2 problems:
 - It doesn't provide very good distinction between a Profile and a Result
 - It doesn't do a very good job of showing that comparison View doesn't work with Profiles.

Suggested solution:

<img width="370" alt="Screen Shot 2020-08-19 at 7 38 42 PM" src="https://user-images.githubusercontent.com/2308869/90700341-9947bd80-e253-11ea-88ae-118246641cdb.png">

When a Profile is selected, the Results and Comparison views should be deselected, and the checkboxes next to the Results should be greyed out. This should only allow for 1 profile to be selected at a time.

**Comment by ejaronne** [comment]
Suggestion for hamburger menu:

Views
- Results View
- Results Comparison View
- Profile View

Results (collapsible)

Profiles (collapsible)

Tools

Info

When you click on Results View or Results Comparison View, the Results list expands, you choose see the view building to the right/behind. click off of the menu to the right to collapse the side menu. (maintain state for the selected set of results)

When you click on Profile View, the Profiles list expands, you choose see the view building to the right/behind. click off of the menu to the right to collapse the side menu. (maintain state for the selected set of profiles)

much cleaner!

**Comment by ejaronne** [comment]
"evaluations" should be changed to "results"
"reports" should be changed to "result sets"

**Comment by ejaronne** [comment]
Results
   list
   X compare
Profiles
   list

**Comment by dmokllm** [comment]
Additional information to the above layout:

- when no file is loaded of a certain type, Results or Profiles, still show the drop down and any options
- only one drop down can be open at a time
- expanding a drop down will activate that view (e.g., expanding Profiles dropdown will automatically activate that view)
- when loading a file of a certain type, activate the view for that file.  when loading multiple files of multiple types, maintain the current default behavior of expanding the Results view
- in the above diagram, [https://github.com/mitre/heimdall2/issues/69#issuecomment-691233492](url), Results and Profiles are dropdowns and compare is a toggle to switch between the Results and Comparison view only (not between Profiles and Comparison view)

**Comment by ejaronne** [comment]
Ooh - if there are no results files loaded yet, and one clicks on the results button, immediately bring up the Load dialog. Likewise for profiles when no profiles are loaded yet.

**Comment by rbclark** [comment]
> Ooh - if there are no results files loaded yet, and one clicks on the results button, immediately bring up the Load dialog. Likewise for profiles when no profiles are loaded yet.

This sounds like rather jarring behavior, normally expanding a dropdown does not change the page you are on, dropdowns are normally only intended to show/hide information. Less jarring would just be showing "No Results/Profiles are currently loaded"
