### ISSUE TITLE
[BUG] Please restore word wrapping for `test` column for failed controls.

### ISSUE THREAD

**Issue by rx294** [mitre/heimdall2#761]
Please restore word wrapping for `test` column for failed controls.

![image](https://user-images.githubusercontent.com/17052944/104534682-b904c700-55e2-11eb-92e4-2c46143371c6.png)

Reproduce:
Load RedHat Eval results from samples and view the failed control `Test` panels.

**Comment by ejaronne** [comment]
I just noticed this too. Thanks!
