### ISSUE TITLE
CAAT enhancements

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#770]
{This seems like an easy fix for a new SAF team member.}

- [x] include message field in the "Test Result Description" for both failed *and passed* controls. 
_(Because the message field is now populated for attested "passed" controls using the new inspec-reporter-json-hdf plugin.)_

Include *all* results in the CAAT output, not just ones that are passed or failed or impact != 0.0.
Here's how to populate their differences:
- [x] for skipped controls, include status (skipped) and "skip_message" field in "Test Result Description" field
- [x] for skipped controls (status of "skipped"), set "Test Result" to "Other Than Satisfied"
- [x] for results with impact 0.0 (N/A), set "Impact" field to "none"

Readability:
- [x] Fix the conversion of \n to the type of line feeds used in Excel, especially for "Weakness Description" (desc) "Test Objective" (tag check or desc check), "Test Result Description" (status + message/skip_message), and "Recommended Corrective Actions" (tag fix or desc fix).
fixes #58 

One small additional tweak I've been meaning to mention:
- [x] for "Impact" field, it was supposed to say "Moderate" for what we call "Medium"

**Comment by rbclark** [comment]
Can you or @rx294 include an attestation example for testing here?

(Also should we include an attestation example in samples?)

**Comment by ejaronne** [comment]
https://github.com/ejaronne/cms-ars-3.1-manual-controls-baseline/blob/main/samples/cms-ars-3.1-manual-controls-baseline_01142021A.json

**Comment by ejaronne** [comment]
I know this might be a reach, and can be addressed in a future PR, but is there any way to do Excel formatting e.g., left/top justified, auto-wrap text in cells, column widths, cell colors, freeze panes, data filtering configured?
