### ISSUE TITLE
Packaging Heimdall Server

### ISSUE THREAD

**Issue by camdenmoors** [mitre/heimdall2#782]
>The issue is we aren't packaging the application in a meaningful installer, we are basically making users build it and run it, so the instructions are very similar. I'm not sure where the requirement came from for manual installation instructions but I'd much rather look at some sort of npx packaging or something similar for Heimdall Server instead of providing manual instructions like this.

_Originally posted by @rbclark in https://github.com/mitre/heimdall2/pull/757#issuecomment-758898789_

Here's some ideas that could work, which have the ability of setting up the database:

Debian Packages: [Tutorial](https://wiki.debian.org/Packaging/Intro?action=show&redirect=IntroDebianPackaging)

RHEL/CentOS Packages: [Official Tutorial](https://rpm-packaging-guide.github.io/) | [Other Tutorial](https://opensource.com/article/18/9/how-build-rpm-packages)

Install Script: [Example](https://github.com/icy/pacapt/blob/master/pacapt#L168)

While I'm not sure if Windows support is still an option, but completeness sake: [MISX Packages](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/create-app-package) | [Install Shield](https://www.revenera.com/install/products/installshield.html)

**Comment by rbclark** [comment]
At this time we really don't have plans to deploy with any method other than Docker. We can reopen this in the future if plans change.
