### ISSUE TITLE
[BUG] Running Heimdall Server on Docker (Debian10)

### ISSUE THREAD

**Issue by ucantravel** [mitre/heimdall2#787]
**Describe the bug**
I followed all the steps to run the enterprise version in docker, but the front end does not seem to work at all. There is a empty web page and in the source I can see an error message saying that javascript must be enabled in the browser. Obviously it is enabled
**To Reproduce**
Just follow the docker installation steps as documented here.

**Expected behavior**
The front-end should be up and running.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141 

**Server version:**
Debian 10

**Comment by rbclark** [comment]
Since you are running on Windows, how did you go about running the `setup-docker-secrets.sh` script? This script will most likely fail on Windows due to it being a bash script which is only designed for Linux. In place of that script, you should be able to manually create two files next to your docker-compose.yml file:

`.env`:
```
DATABASE_PASSWORD=ReplaceThisWithARandomString
```

`.env-prod`:
```
JWT_SECRET=ReplaceThisWithARandomString
JWT_EXPIRE_TIME=24h
```

**Comment by ucantravel** [comment]
Sorry, my mistake: the server is running Debian 10., so I had no problems following all the steps.
My client is running windows.

**Comment by ucantravel** [comment]
The full message in the source of the empty page it says "

  | <!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="./favicon.ico"><title>Heimdall</title><link href="css/chunk-vendors.e7454e75.css" rel="stylesheet"><link href="css/app.c51862af.css" rel="stylesheet"></head><body><noscript><strong>We're sorry but heimdall-lite doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="js/chunk-vendors.43be1350.js"></script><script src="js/app.a05f63c7.js"></script></body></html>
-- | --

"

**Comment by rbclark** [comment]
In that case I'm a little unsure what issue you are encountering. Can you provide the logs from `docker-compose up`? On a clean Docker install it should just be 3 steps to have it up and running. One thing to try may be running `docker-compose down` and then `docker-compose up` again and seeing if there are any errors being reported in Docker.

**Comment by ucantravel** [comment]
I see this error: (I am running the docker under root user, so not sure why the error. Under which user is trying to read that file?)

$ yarn workspace heimdall-server sequelize-cli db:migrate
server_1    | $ ts-node node_modules/.bin/sequelize db:migrate
server_1    | 
server_1    | Sequelize CLI [Node: 14.15.4, CLI: 6.2.0, ORM: 5.22.3]
server_1    | 
server_1    | Attempting to read configuration file `.env`!
**server_1    | Unable to read configuration file `.env`!**
**server_1    | Does the file exist and is it readable by the current user?**
**server_1    | Falling back to environment or undefined values!**
server_1    | Loaded configuration file "db/database.ts".
server_1    | No migrations were executed, database schema was already up to date.
server_1    | Done in 6.87s.
server_1    | yarn run v1.22.5
server_1    | $ yarn workspace heimdall-server sequelize-cli db:seed:all
server_1    | $ ts-node node_modules/.bin/sequelize db:seed:all
server_1    | 
server_1    | Sequelize CLI [Node: 14.15.4, CLI: 6.2.0, ORM: 5.22.3]
server_1    | 
server_1    | Attempting to read configuration file `.env`!
server_1    | Unable to read configuration file `.env`!
server_1    | Does the file exist and is it readable by the current user?
server_1    | Falling back to environment or undefined values!
server_1    | Loaded configuration file "db/database.ts".
server_1    | == 20200514154327-create-administrator: migrating =======
server_1    | Administrator exists. Skipping creation.
server_1    | == 20200514154327-create-administrator: migrated (0.075s)
server_1    | 
server_1    | Done in 6.65s.
server_1    | yarn run v1.22.5
server_1    | $ yarn workspace heimdall-server start
server_1    | $ node ../../dist/server/src/main
server_1    | [Nest] 167   - 01/20/2021, 3:23:34 PM   [NestFactory] Starting Nest application...

**Comment by ucantravel** [comment]
The .env and .env-prod files have 664 permissions.

**Comment by rbclark** [comment]
That message is stating that it is using environment variables, that is expected when running with Docker since Docker provides the values from `.env` and `.env-prod` via environment variables to the application. That startup log seems fine, could you provide a screenshot from the network tab from your browser when the page is loading? Also can you try a separate browser to try to see if this is some strange browser caching issue?

**Comment by ucantravel** [comment]
The error is: ERR_SSL_PROTOCOL_ERROR

![image](https://user-images.githubusercontent.com/45268584/105200300-8bdd7a80-5af4-11eb-89e1-785324eadff0.png)

**Comment by rbclark** [comment]
Can you ensure that you are accessing `http://localhost:3000` and not `https://localhost:3000`? Also if that doesn't work can you modify the `docker-compose.yml` to use a port other than port 3000 (perhaps 8000) and then stop and restart the `docker-compose` script?

**Comment by ucantravel** [comment]
Yes, I am trying http:// but it seems that all the failed calls under the network tab go to https:// 

I have change the port to 8080 and now is not showing anything but connection refused. The docker seems to be running on this new port:

docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-01-20 14:58:07 UTC; 1h 19min ago
     Docs: https://docs.docker.com
 Main PID: 25138 (dockerd)
    Tasks: 18
   Memory: 1.1G
   CGroup: /system.slice/docker.service
           ├─ 2308 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.22.0.3 -container-port 8080
           └─25138 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

Jan 20 16:07:15 mds-dem-d-cin-nane1-heimdall dockerd[25138]: time="2021-01-20T16:07:15.556590164Z" level=info msg="ignoring event" container=1d876b17e00d721df2d...skDelete"
Jan 20 16:08:30 mds-dem-d-cin-nane1-heimdall dockerd[25138]: time="2021-01-20T16:08:30.662134147Z" level=info msg="Firewalld: interface br-1d861ad950d5 already ...eturning"
Jan 20 16:08:31 mds-dem-d-cin-nane1-heimdall dockerd[25138]: time="2021-01-20T16:08:31Z" level=info msg="Firewalld: docker zone already exists, returning"
Jan 20 16:08:32 mds-dem-d-cin-nane1-heimdall dockerd[25138]: time="2021-01-20T16:08:32Z" level=info msg="Firewalld: docker zone already exists, returning"
Jan 20 16:11:48 mds-dem-d-cin-nane1-heimdall dockerd[25138]: time="2021-01-20T16:11:48.383653202Z" level=info msg="Container 968933da53d7b258262bffb400bd4482e0a...he force"
Jan 20 16:11:48 mds-dem-d-cin-nane1-heimdall dockerd[25138]: time="2021-01-20T16:11:48.459255276Z" level=info msg="ignoring event" container=968933da53d7b258262...skDelete"
Jan 20 16:11:48 mds-dem-d-cin-nane1-heimdall dockerd[25138]: time="2021-01-20T16:11:48.744894369Z" level=info msg="ignoring event" container=0e13ccc1a6b87fa46e2...skDelete"
Jan 20 16:12:31 mds-dem-d-cin-nane1-heimdall dockerd[25138]: time="2021-01-20T16:12:31.833062400Z" level=info msg="Firewalld: interface br-c9744445299b already ...eturning"
Jan 20 16:12:32 mds-dem-d-cin-nane1-heimdall dockerd[25138]: time="2021-01-20T16:12:32Z" level=info msg="Firewalld: docker zone already exists, returning"
Jan 20 16:12:33 mds-dem-d-cin-nane1-heimdall dockerd[25138]: time="2021-01-20T16:12:33Z" level=info msg="Firewalld: docker zone already exists, returning"

**Comment by rbclark** [comment]
Just for clarification, it looks like docker is mapping 8080 -> 8080, not 8080 -> 3000. Can you try setting the port as follows:

```yaml
    ports:
      - "8080:3000"
```

**Comment by ucantravel** [comment]
Thanks for the clarification:)

The same problem as before. In the network tab I can see the first request going to http:// and all the next requests going to the https:// and failing due to the ssl error message.

**Comment by ucantravel** [comment]
Internet Explorer gives a different error in the console:

![image](https://user-images.githubusercontent.com/45268584/105207952-04e0d000-5afd-11eb-89e0-662c929e96d2.png)

**Comment by rbclark** [comment]
This issue is happening due to Heimdall Server passing `upgrade-insecure-requests` to the browser. I have created a short-term PR to fix this issue (https://github.com/mitre/heimdall2/pull/790). Once this is merged and the docker build completes you should be able to pull down a new container and be able to access heimdall server via IP address over HTTP. The longer term fix will be https://github.com/mitre/heimdall2/issues/791.

**Comment by ucantravel** [comment]
Great! Thanks. Will test when available.

**Comment by ucantravel** [comment]
I did a "docker-compose pull" to get the latest image but the same problem persist. It keep trying the SSL urls

**Comment by rbclark** [comment]
Unfortunately Dockerhub is excruciating slow to build images. The image with the updated changes is still building. I will keep an eye out and post here when an image with the changes is available.

**Comment by rbclark** [comment]
You should be now safe to do a `docker-compose pull` and `docker-compose up`. One small change I made is by default the `docker-compose.yml` will pull from `mitre/heimdall2:release-latest` instead of `mitre/heimdall2`. In the case of debugging this specific issue I suggest ensuring you are using `mitre/heimdall2` and not `release-latest`.

**Comment by ucantravel** [comment]
Much appreciated your help with this bug! Now it runs perfectly!!!

**Comment by rbclark** [comment]
Glad to hear it worked!
