### ISSUE TITLE
Update README screenshots and demo video

### ISSUE THREAD

**Issue by Bialogs** [mitre/heimdall2#81]
Since the Delta View has been added the screen shots & video are outdated.

**Comment by camdenmoors** [comment]
We didn't make a heimdall demo video, just an install: https://www.youtube.com/watch?v=irFLngy1PCA

**Comment by ejaronne** [comment]
This is referring the old youtube Aaron made as a quick-drive inserted at the top of the README page: https://www.youtube.com/watch?v=1jXHWZ0gHQg 

It's from November 2019, based on 2.0.2. So yes, it is dated. 

There aren't any stills on the README page, if there ever were.

The Help in Heimdall screen-shots are pretty current though.
