### ISSUE TITLE
Update Results page to display Profiles

### ISSUE THREAD

**Issue by robthew** [mitre/heimdall2#82]
The results page is designed for Evaluations, but it needs to display uploaded Profiles as well.

To handle Profiles, a few changes are needed: 
1. The result counts and charts are not needed, and can be replaced with a chart showing the counts of severities.
2. The control datatable does not need to display the 'Test' section,  but can keep the 'Info' and 'Code' sections.
3. If this Profile is saved in the database, a table of Evaluations performed against this Profile can be listed (based on the SHA256 value).

**Comment by dmokllm** [comment]
The following comment needs to be addressed when addressing this issue: `https://github.com/mitre/heimdall2/pull/126/#discussion_r485155360`
