### ISSUE TITLE
[BUG] Splunk Upload Tab does not validate hostname

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#90]
**Describe the bug**
The hostname field not validated to ensure that it is a valid http(s) url before we try to access it. Because of this, if a user puts in something without `http(s)://` in front of it they get very strange behavior depending on how they view the app.

**To Reproduce**
1. Go heimdall-lite
2. Click SPLUNK on the UploadNexus
3. Type in any host but leave off the `http(s)://`

![output](https://user-images.githubusercontent.com/3009651/88967902-7477b000-d27c-11ea-991c-681a7b542146.gif)

**Expected behavior**
The hostname should be highlighted in red since it is invalid, and I should not be redirected to view results.

**Comment by Amndeep7** [comment]
![image](https://user-images.githubusercontent.com/2015821/151713929-f7fafa15-11fc-4b3d-b0c4-2922ffd54d29.png)

Get a incorrect username/password error, which still isn't clear but at least you don't go to the next page in the modal.  I think we don't need to validate the existence of the hostname, just if the credentials work wherever they try to send us so I'm gonna close this issue.  If necessary, we make a new one to clarify the error statement.
