### ISSUE TITLE
Implement Grouping on Database Results

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall2#906]
Currently all of the Database entries are shown as one large list on the Database page.

![Screen Shot 2021-02-08 at 6 37 14 PM](https://user-images.githubusercontent.com/2308869/107295077-ac865980-6a3c-11eb-9bef-aae5ade48aa5.png)

It would be better now that we have different types of evaluations to organize these by different groups:

![Screen Shot 2021-02-08 at 6 41 00 PM](https://user-images.githubusercontent.com/2308869/107295366-359d9080-6a3d-11eb-803b-c006c3f82d01.png)

These groups should be:

 - My Files
 - Public Files
 - (Group X) Files
 - (Group Y) Files
 - etc

**Comment by rbclark** [comment]
Blocked until #794 is merged.

**Comment by ejaronne** [comment]
We should also be able to search by Group.

**Comment by rbclark** [comment]
Superseeded by #906
