### ISSUE TITLE
Update CAAT output to allow "Critical" impact

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#93]
In addition to the current Low, Medium, High values allowed into the Impact field, allow "Critical" to be placed there if the results mark a test as Critical (i.e., 0.9-1.0)

**Comment by ejaronne** [comment]
I think this was already corrected somewhere along the way. When loading the ACME Overlay Example (which has critical defects) they show up in the CAAT export.

**Comment by camdenmoors** [comment]
Just tested it, critical Impacts do show.
