### ISSUE TITLE
Comparison view fails to show code as the results view does for overlays

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#941]

**Comment by camdenmoors** [comment]
Currently unable to replicate this, does this still happen for you?

![image](https://user-images.githubusercontent.com/66680985/109179594-0fbffd80-7758-11eb-8d24-202a47c10800.png)

**Comment by ejaronne** [comment]
Not all controls are overlayed in that result set. V-61447 is a good example:

![image](https://user-images.githubusercontent.com/34140975/109181175-a17c3a80-7759-11eb-9d20-44404fd7c857.png)
vs:
![image](https://user-images.githubusercontent.com/34140975/109181363-d5eff680-7759-11eb-95a4-89d3ebc2ecc6.png)
