### ISSUE TITLE
Add "tab synchronize" button in results view

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall2#943]
similar to comparison view: all tests, or all details, or all code

**Comment by camdenmoors** [comment]
Not exactly sure what's meany by this, can you post a screenshot from the comparison view what you would like to see on the results page?

**Comment by rbclark** [comment]
This but down the page for all of the Test, Details, and Code tabs.
![tabsync](https://user-images.githubusercontent.com/2308869/108533194-b747b680-72a6-11eb-9acf-4bc32a747e3f.gif)
